### ISSUE TITLE
BUG: Can't seem to recognize music

### ISSUE THREAD

**Issue by KarthikJay** [KieronQuinn/AmbientMusicMod#1]
Device: Mi 10 Ultra
ROM: [EU MIUI 12.6](https://xiaomi.eu/community/threads/21-4-7-8.60699/) 

Issue:
Installed magisk and LSPosed modules.
Tried manual test recognition, got nothing back after recording.
Also track database doesn't seem to load?

Logs:
[ambient_music_mod_log_dump_2021-04-16T04_17_19.47.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/6324581/ambient_music_mod_log_dump_2021-04-16T04_17_19.47.zip)

I added whitelist for System Framework and Pixel Ambient Services.

**Comment by KieronQuinn** [comment]
Hi,

Could you send the file /system/vendor/etc/sound_trigger_platform_info.xml too please? The current version manages to corrupt the xml when adding it to the zip, it's fixed in the next version.

The error suggests either one of two things:
- SoundTriggerManager.getModelState() isn't supported by your device and so it will likely never work
- You're just missing one line from the XML that is already confirmed working for someone else. 

Let's try suggestion 2 first :)

**Comment by KarthikJay** [comment]
Sure thing, here it is:

[sound_trigger_platform_info.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/6327144/sound_trigger_platform_info.zip)

**Comment by KieronQuinn** [comment]
On further examination on my P2XL which does the same thing with the module, I think it's actually the model it doesn't like. 

But I've got another thing to try instead. Extract this zip: 
[attempt1.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/6327459/attempt1.zip)

Place music_detector.descriptor and music_detector.sound_model in /data/adb/modules/AmbientMusicTest/system/product/etc/firmware
and place sound_trigger_platform_info.xml in /data/adb/modules/AmbientMusicTest/system/vendor/etc

Overwrite files if they exist.

Reboot.

After this, Ambient Music _may_ work, but the option to manually start listening will not. Just be patient, try a few songs and dump the logs again if it's not working still.

**Comment by KarthikJay** [comment]
Tried it for a day, doesn't seem to be working still unfortunately.

Here's another dump:
[ambient_music_mod_log_dump_2021-04-17T11_00_24.907.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/6329754/ambient_music_mod_log_dump_2021-04-17T11_00_24.907.zip)

**Comment by KieronQuinn** [comment]
Yeah the error log shows that's failing with the same error (unable to load the model)

There's nothing I can do here unfortunately, your device doesn't seem to like the models. 

Track list however is fixed in the next version.
