### ISSUE TITLE
Create a custom ROM integration service

### ISSUE THREAD

**Issue by ralph950412** [KieronQuinn/AmbientMusicMod#100]
**This is not a bug report, it's just a suggestion!**
A custom ROM integration, with the exact same Now Playing feature Google Pixel provides, and left the extra customizations to the Ambient Music Mod app itself, would be nice.
Also, shizuku / sui may no longer being required on ROMs that integrate it.

**Comment by KieronQuinn** [comment]
Not possible, the mod requires permissions only granted to platform apps so global custom ROM integration is not going to work, otherwise I'd have made a Magisk module for it. Use Sui.

**Comment by e-t-l** [comment]
@KieronQuinn

> the mod requires permissions only granted to platform apps

Just thinking this through... What about creating a small helper app that could be granted the necessary permissions in odder for the ROM-integrated aspects to work? Especially because some ROMs like Graphene disallow apps to send ADB commands, meaning Shizuku can't run.

**Comment by KieronQuinn** [comment]
> @KieronQuinn
> 
> > the mod requires permissions only granted to platform apps
> 
> Just thinking this through... What about creating a small helper app that could be granted the necessary permissions in odder for the ROM-integrated aspects to work? Especially because some ROMs like Graphene disallow apps to send ADB commands, meaning Shizuku can't run.

The permissions are signature locked, so it's not as simple as just a helper app, it would need to be built during the ROM build process, a system I have absolutely no experience with.
