### ISSUE TITLE
Database won't download

### ISSUE THREAD

**Issue by saiskandapgs** [KieronQuinn/AmbientMusicMod#101]
Sorry to open a new issue on this again. I noticed your app does not have the permission to store files. Is this stopping the download. I have tried the other ways - reboot, disable wifi only download etc.

I'm unable to manually grant it storage access.

Let me know, thanks for the great work on this!

**Comment by saiskandapgs** [comment]
Ok I tried something that worked. I opened the app settings for Now Playing and cleared all data. After this, opening up ambient music mod and enabling it. It downloaded it successfully!

**Comment by KieronQuinn** [comment]
The storage permission is not required as it uses internal app storage, not external storage.

**Comment by jschenke488** [comment]
> Ok I tried something that worked. I opened the app settings for Now Playing and cleared all data. After this, opening up ambient music mod and enabling it. It downloaded it successfully!

Thanks. This worked, but do you know of any way to fix this without clearing all the data? I would rather not change my settings every time this happens.

**Comment by jschenke488** [comment]
To be specific, the error I'm experiencing is that the database seems to download, but never stops downloading unless I clear data and try again.

**Comment by saiskandapgs** [comment]
> To be specific, the error I'm experiencing is that the database seems to download, but never stops downloading unless I clear data and try again.

Yeah I know exactly what you are facing. Restarting the phone has also worked for me. Once during an update I just let it be for a day and it eventually fixed itself.

**Comment by saiskandapgs** [comment]
> > Ok I tried something that worked. I opened the app settings for Now Playing and cleared all data. After this, opening up ambient music mod and enabling it. It downloaded it successfully!
> 
> Thanks. This worked, but do you know of any way to fix this without clearing all the data? I would rather not change my settings every time this happens.

I take a backup before clearing data. That helps too. As soon as it opens up, you can restore settings and now playing history.

**Comment by BadKiko** [comment]
Yes, this help me, thanks!
