### ISSUE TITLE
Unable to build NowPlaying

### ISSUE THREAD

**Issue by Fede2782** [KieronQuinn/AmbientMusicMod#102]
Hi, I know this isn't important, but I was trying to build NowPlaying (Ambient Music Mod is ok) but it doesn't produce any outputs (no files, apk). Using directly gradlew it has an error:

"
 What went wrong:
Execution failed for task ':copyOverlay'.
 from.listFiles() must not be null
"

I followed the instructions multiple times but it still doesn't work.
https://scans.gradle.com/s/2affcnqv62li2

Using Android Studio it says that the build finished successfully but the output isn't present. 

I am willing to close the question if I have not written it in the right place.

Sorry for troubling and for my english

**Comment by KieronQuinn** [comment]
Fixed, sorry for the delay. It was trying to copy a dir that was never pushed as it was empty.
