### ISSUE TITLE
I get a warning

### ISSUE THREAD

**Issue by fabi21ag** [KieronQuinn/AmbientMusicMod#105]
I get a warning: An app is using device audio (songs aren't identified while device audio is being used by others apps) 
somebody could help me?
![Screenshot_2022-09-04-12-20-43-915_com kieronquinn app ambientmusicmod](https://user-images.githubusercontent.com/112820577/188329181-4d2c9bf9-3461-4959-a7fa-0a441727925d.jpg)

**Comment by KieronQuinn** [comment]
That message means music is being played by the device. The data is coming from the system and is the same method used by Now Playing to prevent recognitions, so it can't be disabled.

**Comment by fabi21ag** [comment]
> 

so i can't do anything to solve it?

**Comment by KieronQuinn** [comment]
If you're not playing music on the device, no.
