### ISSUE TITLE
Manually detected songs keeps being shown in Lockscreen when disabled recognition (Bed time mode)

### ISSUE THREAD

**Issue by FuSan21** [KieronQuinn/AmbientMusicMod#106]
Steps to reproduce:
1. Activate bedtime mode schedule and proceed when that is active.
2. Manually recognize a song from inside app.
3. Music name is kept showing in Lockscreen even after long time. (Assumption: Probably until new song isn't recognized or bed time mode is disabled)

Expected result:
Music name is Shown until the song is finished. Then cleared. Based on recognizing how long it needs to end.

Device: K20 Pro
Android 13 AOSP rom

**Comment by KieronQuinn** [comment]
Fixed in 2.1
