### ISSUE TITLE
Oneplus 8T - using bottom mic (intended for calls) instead of top one (intended for ambient sound recongition)

### ISSUE THREAD

**Issue by kulmegil** [KieronQuinn/AmbientMusicMod#11]
Problem:

Judging by terrible quality of any input playback from recognition test + fact that device needs to be directed specifically at the sound source + having to be relatively close to sound source - the wrong mic is being used.

That is a directional mic (located at the bottom of device) that is designed for recording voice during phone calls and not being optimal for ambient sounds.

Solution:
Is it possible to switch to the main mic (located at the top of device) that is probably designed to recognize ambient sounds?

AmbientMusicMod: 1.1.1
EdXposed: 0.5.2.2 (Yahfa)
Magisk: 22104 (latest canary build)
OS: OxygenOS 11.0.8.12 (stock rom, Android 11 based)

**Comment by KieronQuinn** [comment]
I tried to do this in development, but I was unable to get it to work. It uses the 'assistant' mic source (and has to otherwise it'll interfere with other stuff), which makes sense when you consider it's usually for voice recording normally.
