### ISSUE TITLE
An app is using device audio, but no application is.

### ISSUE THREAD

**Issue by SpacEagle17** [KieronQuinn/AmbientMusicMod#111]
The app works when triggering manually, but it doesn't work automatically as the warning of another app using the device audio is there, even though no app is actually playing sounds.

Ambient Music Mod: 2.0.5, Now playing: 1.0.3, Shizuko version: 12.12.0.r885.287b4eb
Used USB debugging via PC to connect to Shizuko

MIUI version for Poco: Global 13.0.8 Stable 13.0.8.0(SKHEUXM), Phone: Poco F3, Android version: 12 SKQ1.211006.00, Android security update: 2022-08-01

![Screenshot_2022-10-05-22-15-01-917_com.mi.android.globallauncher.jpg](https://user-images.githubusercontent.com/46494907/194154877-ad8bbe39-cd3f-4654-a72f-bc60b5203762.jpg)
![Screenshot_2022-10-05-22-14-58-390_com.kieronquinn.app.ambientmusicmod.jpg](https://user-images.githubusercontent.com/46494907/194154905-2e8bdf78-a464-455d-a9c9-f1f3e3b3dde0.jpg)

**Comment by KieronQuinn** [comment]
Something _is_ using audio, that is coming from the system. However, it's not necessarily visible as it doesn't have to be music. There could be a background app "playing" silence. 

There isn't anything I can do in this case, disabling the check would simply result in broken recording.

**Comment by SpacEagle17** [comment]
That's unfortunate, I'll try to find which app is _playing_ audio. Thanks though

**Comment by KieronQuinn** [comment]
The original Now Playing app actually tells you which app is using it, but unfortunately that requires a system permission that Shell does not have so I couldn't replicate it.

**Comment by SquadCraftFTW** [comment]
I had the same issue, but when I restart the error disappears and it turns out AMM was listening to songs in the background the entire
