### ISSUE TITLE
Microphone Static When Recording Audio

### ISSUE THREAD

**Issue by JaredStock20** [KieronQuinn/AmbientMusicMod#114]
Hi,

Phone Model: Samsung Note 10 Plus
Software Version: Android 12, One UI 4.1
App Version: 
Ambient Music Mod 2.0.5
Now Playing: 1.0.3

When I try to manually scan for playing songs, it is unable to recognize any music and the microphone only pics up a large amount of static. (See video.) The application has been unable to recognize any song when the phone is locked. (Now Playing says it has no recognitions yet.)

This issue persists when I reboot the phone, re-install the applications, and re-install shizuku.

Please let me know if you need any more information. Thank you.

![Screenshot_20221020-121330_Ambient Music Mod](https://user-images.githubusercontent.com/34488610/197038201-b67d3744-43c1-447b-a830-1ae4a6d4a198.jpg)

![Screenshot_20221020-121243_Software update](https://user-images.githubusercontent.com/34488610/197038217-24c38f2e-6d66-49b6-965f-098551cd8ced.jpg)

https://user-images.githubusercontent.com/34488610/197038235-bdd51b64-75e1-4d72-8a96-719154376e03.mp4

**Comment by KieronQuinn** [comment]
Enable alternative encoding in the advanced settings.
