### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [KieronQuinn/AmbientMusicMod#115]
I see most of the used libraries etc. are under Apache-2.0 – but the app itself declares no license. Was it just missed to add it? Could you please clarify what license is used for the app itself? Thanks in advance!

**Comment by KieronQuinn** [comment]
Oops, should be GNU v3 - same as my other apps. Added.

**Comment by IzzySoft** [comment]
Thought so, but wasn't sure (some are Apache :wink: 

As your other apps, stgarting with the next sync at around 6 pm UTC it will become available in my repo then. Thanks a lot!

For reference, please [see here](https://apt.izzysoft.de/fdroid/?author=Kieron+Quinn) – and be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there, e.g. from the corresponding Readmes.
