### ISSUE TITLE
Cannot Recognise Song

### ISSUE THREAD

**Issue by PeithonKing** [KieronQuinn/AmbientMusicMod#118]
(Assuming I installed it correctly and gave it all the permissions... Actually I gave all the permissions)

Problem: It is not being able to recognise any song... First I played a Bengali song, then I played Despacito (assuming Despacito must be in its library) it recognised nothing.

Probable Problem: It has a playback option... so when I click on it, it plays a noise... I have tried playing the song multiple times, in different ranges of volumes... no change... all we get is noise... no wonder it cannot recognise the song.

Have I made any mistake while installations? or is this a bug?

**Comment by KieronQuinn** [comment]
Enable alternative encoding in the advanced settings.
