### ISSUE TITLE
App stuck updating

### ISSUE THREAD

**Issue by ArcherB6** [KieronQuinn/AmbientMusicMod#120]
![Screenshot_20221030-141528_Ambient Music Mod](https://user-images.githubusercontent.com/76863061/198862308-8fb659d2-9147-4c3a-bed6-3923c0c71a2d.jpg)
I have only just downloaded the app and it works great but when I try updating the Music Database it gets stuck updating for hours and never finishes. I'm using the latest 2.0.5 version on samsung.

**Comment by KieronQuinn** [comment]
#57
