### ISSUE TITLE
The mod works with battery saver disabled but not with saver enabled 

### ISSUE THREAD

**Issue by Kronodile** [KieronQuinn/AmbientMusicMod#123]
I have run on battery saver option enabled from the app's settings but it doesn't seem to work.

On demand and offline works perfectly fine, so does the lockscreen mode with battery saver off but I usually have battery saver enabled so it would be so helpful.

I also have the app set to "unrestricted" in battery option

Device: Poco F3 (alioth)
Rom: Ancient OS 12.1 
App version: all latest. 
Google: 13.44.9.29
Ambient music mod: 2.0.5
Now playing: 1.0.3

**Comment by KieronQuinn** [comment]
Unfortunately it seems the running when battery saver is enabled option didn't actually work - there's a flag for it, but it no longer makes any difference to the actual recognition. I've removed the toggle in 2.1.
