### ISSUE TITLE
Downloading database version 234 for over 8hrs

### ISSUE THREAD

**Issue by CynfalYin** [KieronQuinn/AmbientMusicMod#124]
I recently installed the app to try it out, and clicked the update link because I thought I should. Since midnight last night, it's been updating, with no change to its behavior even when force closed. 

Device: Samsung Galaxy S22 Ultra (SM-S908U1)
OS: OneUI 5.0 / Android 13
Ambient Music Mod 2.0.5
Now Playing 1.0.3

Will likely attempt to uninstall and reinstall, but I still thought it was worth mentioning.

**Comment by KieronQuinn** [comment]
#57
