### ISSUE TITLE
Audio highly scuffed or corrupted

### ISSUE THREAD

**Issue by Bluemethyst** [KieronQuinn/AmbientMusicMod#129]
Hey, just started using this on my Oppo A94 5G and i got it installed all fine with Shizuku and it runs and installed the database but when i try to recognize a song with it it never ever works even with the most well known songs and when i listen to the playback of it its all windy and fuzzy and its not a problem with my phone as i went into several other apps and the mic worked perfectly. I adjusted the gain and went through all the settings and nothing has worked. If u dont already have a fix i can sent through an audio recording if you want.
ty :)

**Comment by KieronQuinn** [comment]
Enable alternative encoding in the advanced settings.
