### ISSUE TITLE
Music database download stuck forever

### ISSUE THREAD

**Issue by SquadCraftFTW** [KieronQuinn/AmbientMusicMod#131]
The music database download for version 238 (not sure if it's the version being downloaded or the one that's already installed) is constantly showing up as currently downloading in the updates section, however it never seems to download. My bandwidth measurement is only giving me a few kbps from android system and Google play system services, so no download is occuring. 

I've tried disabling the "Database Downloads on Wi-Fi only" setting and restarting, as well as just normally restarting and then using mobile data, to no avail.

Edit: I've tried resetting the app and changing my region from "automatic" (I'm located in the UK) to US or manually selecting UK and the same issue occurs. 

Device: Poco F2 Pro (lmi)
Rom: Xiaomi EU (13.0.6)
Google: 13.48.11.29
Ambient music mod: 2.0.5
Now playing: 1.0.3

**Comment by KieronQuinn** [comment]
#57
