### ISSUE TITLE
Mic sounds like wind passing by, but works normally in other apps...

### ISSUE THREAD

**Issue by Keklllelll** [KieronQuinn/AmbientMusicMod#136]
Soy i found out that the mic Recording of the app sounds like wond passing by and you cant hear anything than that, BUT my mic works normally in other apps....🫠🫤 idk what to do

Turn on your volume ⬇️⬇️:
https://user-images.githubusercontent.com/121905117/210448360-7befa90b-46b3-4523-b579-72156e0e702b.mp4

-Bye

**Comment by KieronQuinn** [comment]
Enable alternative encoding in the advanced settings.
