### ISSUE TITLE
Static Sound

### ISSUE THREAD

**Issue by BurntDosa** [KieronQuinn/AmbientMusicMod#140]
It does not take any input from mic and there is just a static sound when I play back the audio.

**Comment by brianjmurrell** [comment]
How is this (closed) as _completed_? I.e. what was done to complete it?

I ask because I have this problem and this ticket is not explaining how it was resolved.

**Comment by KieronQuinn** [comment]
Likely because they realised it's a common issue and read the pinned issue #173, which explains how to resolve it. It's not a bug.
