### ISSUE TITLE
Recording pure noise

### ISSUE THREAD

**Issue by lucastwg** [KieronQuinn/AmbientMusicMod#141]
On Xiaomi mi 11s, after completing setup and trying to identify a song on the main screen. It always fails and playback is pure saturated noise.
Importing the .pcm file into audacity shows that the audio is there, in a different channel:  [https://imgur.com/a/vrP97V7]() but is completely overpowered by the noise, so it can't identify anything.

Device: Xiaomi mi 11s
OS: MIUI 13, Android 12.
Not Rooted, set up with Shizuku.

**Comment by KieronQuinn** [comment]
Enable alternative encoding in the advanced settings.
