### ISSUE TITLE
Now Playing v1.1.1 crashing

### ISSUE THREAD

**Issue by rodrigoswz** [KieronQuinn/AmbientMusicMod#146]
Since I updated it, I have the Now Playing force closed dialog pretty much every time I unlock my phone.

- POCO F3
- Android 13
- AMM 2.1.1
- Now Playing 1.1.1

Crash log from my ROM: https://bin.kv2.dev/~63ed88cbe599576ea02bb6c2
Logcat: [logs-2023-02-15-21-55-54.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/10751109/logs-2023-02-15-21-55-54.zip)
[logs-2023-02-15-21-35-14.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/10751136/logs-2023-02-15-21-35-14.zip)

**Comment by KieronQuinn** [comment]
```
time: 1676511912249
--
  | device fp:POCO/alioth_global/alioth:12/SKQ1.211006.001/V13.0.6.0.SKHMIXM:user/release-keys
  | product board:kona
  | superior vers:SuperiorOS-Thirteen-alioth-GAPPS-RELEASE-20230212-1250
  | msg: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
  | stacktrace: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 } in fpx@3787329
  | at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
  | at android.app.LoadedApk$ReceiverDispatcher$Args$ExternalSyntheticLambda0.run(Unknown Source:2)
  | at android.os.Handler.handleCallback(Handler.java:942)
  | at android.os.Handler.dispatchMessage(Handler.java:99)
  | at android.os.Looper.loopOnce(Looper.java:201)
  | at android.os.Looper.loop(Looper.java:288)
  | at android.app.ActivityThread.main(ActivityThread.java:7867)
  | at java.lang.reflect.Method.invoke(Native Method)
  | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  | Caused by: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
  | at android.provider.DeviceConfig.enforceReadPermission(DeviceConfig.java:1212)
  | at android.provider.Settings$NameValueCache.getStringsForPrefix(Settings.java:3286)
  | at android.provider.Settings$Config.getStrings(Settings.java:18352)
  | at android.provider.DeviceConfig.getProperties(DeviceConfig.java:811)
  | at android.provider.DeviceConfig.getProperty(DeviceConfig.java:783)
  | at android.provider.DeviceConfig.getInt(DeviceConfig.java:863)
  | at jvu.a(Unknown Source:5)
  | at etq.i(PG:9)
  | at etq.c(PG:2)
  | at dwx.e(PG:3)
  | at dwx.d(Unknown Source:10)
  | at dwp.d(Unknown Source:22)
  | at doq.d(Unknown Source:9)
  | at dnt.f(PG:2)
  | at bva.aC(PG:24)
  | at bvh.g(PG:70)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bvh.g(PG:72)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bvh.g(PG:73)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bvh.g(PG:75)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bvh.g(PG:76)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bvh.g(PG:79)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bvh.g(PG:80)
  | at bvh.a(PG:311)
  | at rkf.a(PG:1)
  | at bva.aQ(Unknown Source:59)
  | at bvh.b(PG:107)
  | at bvh.a(PG:313)
  | at rkf.a(PG:1)
  | at bva.aP(Unknown Source:2)
  | at bvh.b(PG:109)
  | at bvh.a(PG:313)
  | at rkf.a(PG:1)
  | at bvh.b(PG:115)
  | at bvh.a(PG:313)
  | at rkf.a(PG:1)
  | at bvh.b(PG:116)
  | at bvh.a(PG:313)
  | at rkf.a(PG:1)
  | at fpx.onReceive(PG:16)
  | at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
  | ... 9 more
```

**Comment by rodrigoswz** [comment]
Sorry but what?
Do I need to grant this permission to some app?

**Comment by KieronQuinn** [comment]
No, I just copied the log off the linked site. They often delete the logs after a period so things get lost if not copied.

**Comment by e-t-l** [comment]
Is `READ_DEVICE_CONFIG` a newly required permission as of v1.1.1? It's one of the permissions that can only be granted (without root) to apps with the `preinstalled` flag, aka they're shipped with the ROM.

**Comment by KieronQuinn** [comment]
No, all uses of it are patched out. DeviceConfig is hooked in [this class](https://github.com/KieronQuinn/NowPlaying/blob/main/overlay/src/main/java/com/kieronquinn/app/pixelambientmusic/xposed/hooks/DeviceConfigHooks.kt), including the method shown in this crash log. As a result, I can't fix this - if the hooks aren't working, it's out of my control.

**Comment by rodrigoswz** [comment]
Is there something i can try myself? I have root so I would appreciate it if there are any hints of adb command, mod, magisk/xposed module...

Strange that the previous versions works perfectly without any crash.

**Comment by KieronQuinn** [comment]
If simple stuff like rebooting doesn't work, then no. The hooks either work or don't, so if you're seeing a few failing and nobody else is, it's the sign of a more serious issue with the firmware.

**Comment by e-t-l** [comment]
> No, all uses of it are patched out. DeviceConfig is hooked in [this class](https://github.com/KieronQuinn/NowPlaying/blob/main/overlay/src/main/java/com/kieronquinn/app/pixelambientmusic/xposed/hooks/DeviceConfigHooks.kt) 

That's a cool solution to the permission problem! I'm curious about this class (feel free to ignore since these questions are out of scope of this Issue)

It looks like this class only works for root, is that correct? Do you think it's hypothetically possible to make ASI work on unrooted devices by patching the ASI apk directly? Or would that run into signature conflicts with other Android/Google components? (Im thinking specifically about making ASI work on GrapheneOS, which recently became compatible with Shizuku, but doesn't play well with rooting. ASI is necessary to reenable useful features like Automatic Captions and [Smart Text Selection](https://www.androidpolice.com/2018/05/09/android-ps-new-recents-ui-includes-smart-text-selection-image-sharing-pulling-text-images/))

**Comment by KieronQuinn** [comment]
> > No, all uses of it are patched out. DeviceConfig is hooked in [this class](https://github.com/KieronQuinn/NowPlaying/blob/main/overlay/src/main/java/com/kieronquinn/app/pixelambientmusic/xposed/hooks/DeviceConfigHooks.kt)
> 
> That's a cool solution to the permission problem! I'm curious about this class (feel free to ignore since these questions are out of scope of this Issue)
> 
> It looks like this class only works for root, is that correct? Do you think it's hypothetically possible to make ASI work on unrooted devices by patching the ASI apk directly? Or would that run into signature conflicts with other Android/Google components? (Im thinking specifically about making ASI work on GrapheneOS, which recently became compatible with Shizuku, but doesn't play well with rooting. ASI is necessary to reenable useful features like Automatic Captions and [Smart Text Selection](https://www.androidpolice.com/2018/05/09/android-ps-new-recents-ui-includes-smart-text-selection-image-sharing-pulling-text-images/))

It's already rootless, patched ASI with LSplant + Aliuhook is exactly what you describe and the core of how znow Playing works. It may be possible to enable other features in a similar manner to how Ambient Music Mod does, but I've not checked.

**Comment by e-t-l** [comment]
> It's already rootless, patched ASI with LSplant + Aliuhook is exactly what you describe

Oh okay, great! I had assumed it was root only because it's path was in `/xposed/hooks/`. Is the patched ASI apk available to download and install independently?

**Comment by KieronQuinn** [comment]
> > It's already rootless, patched ASI with LSplant + Aliuhook is exactly what you describe
> 
> Oh okay, great! I had assumed it was root only because it's path was in `/xposed/hooks/`. Is the patched ASI apk available to download and install independently?

Yes, the ASI APK is Now Playing. It has a different package name, and every non-Now Playing component disabled though. You would need to write your own patches to use the other components.

**Comment by e-t-l** [comment]
Oh I see what you're saying now. Thanks for taking the time to explain!
