### ISSUE TITLE
An app is recording audio

### ISSUE THREAD

**Issue by saravanasg** [KieronQuinn/AmbientMusicMod#148]
"An app is using device audio (songs aren't identified while device audio is being used by others apps)"
I get this warning everytime i try to recognise a song manually. It goes away and comes back every few seconds. And all it records is static.

Could someone help me?

**Comment by KieronQuinn** [comment]
Your two issues are unrelated.

The warning is normal, the app is itself doing the recording so it's expected (but could maybe be suppressed)

The static issue is because you need to enable alternate encoding in the advanced settings. The app tells you this.

**Comment by saravanasg** [comment]
I've enabled alternate encoding in the advanced settings.
No difference.

**Comment by KieronQuinn** [comment]
Your device is not compatible then. The only way static can come from that microphone with alternate encoding enabled is if the device is sending static. If another app was genuinely recording, it would be silent.

**Comment by saravanasg** [comment]
Is there a way that i can do to make it work?

**Comment by KieronQuinn** [comment]
Different ROM maybe but I can't guarantee that would fix it.
