### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by YashjitPal** [KieronQuinn/AmbientMusicMod#149]
The app is not working after I turned on shizuku. Btw the shizuku showed some limitations. Idk why but I wasn't able to fix that and I also donno how to root and my android is 12. So is there any other app using which I can run this app other than shizuku?

**Comment by KieronQuinn** [comment]
If you're not rooted then no, Shizuku is the only way. What limitations does Shizuku show?

**Comment by YashjitPal** [comment]
> If you're not rooted then no, Shizuku is the only way. What limitations does Shizuku show? 

I don't know but i did everything shizuku needed and this is showing something and I am'nt able to fix this. I read the document but not working as the steps gave use![Screenshot_2023-02-22-13-28-33-00_bbcac0db4b62a7ada9c32b2fb09e1801.jpg](https://user-images.githubusercontent.com/80625891/220559241-1a753c03-e842-4070-b14d-6fdcde7140d6.jpg)

**Comment by KieronQuinn** [comment]
In that case, there is nothing I can do. This is a Shizuku problem, not Ambient Music Mod, and if the instructions on the Shizuku website do not work on your device, there's likely nothing they can do either.
