### ISSUE TITLE
[Request] Last.fm scrobbling

### ISSUE THREAD

**Issue by itsnebulalol** [KieronQuinn/AmbientMusicMod#154]
I'd like to see auto last.fm scrobbling for Now Playing songs. [Scroball](https://github.com/peterjosling/scroball) should be a decent example for scrobbling.

I might end up implementing this for myself in a really hacky way. Putting scrobble code right where the song is shown on the lock screen is probably the easiest way.

**Comment by KieronQuinn** [comment]
Just use [Pano Scrobbler](https://github.com/kawaiiDango/pScrobbler), it already works with Ambient Music Mod. I implemented it on that.

**Comment by itsnebulalol** [comment]
Thanks for the quick reply! That works!
