### ISSUE TITLE
Now Playing Error

### ISSUE THREAD

**Issue by Araide** [KieronQuinn/AmbientMusicMod#159]
It has worked before a reboot of my phone, but now it pops up a "Now Playing Error" text. I'm genuinely quite confused.
![image](https://user-images.githubusercontent.com/105794704/226111636-86a60765-eaa8-46da-831a-9e482faeb5ec.png)

**Comment by KieronQuinn** [comment]
The permissions broke. Uninstall both Now Playing and Ambient Music Mod and start again.

**Comment by Araide** [comment]
How do I uninstall Now playing though?
