### ISSUE TITLE
Audio on bluetooth and alarm breaks with Magisk module enabled

### ISSUE THREAD

**Issue by TheBluekr** [KieronQuinn/AmbientMusicMod#16]
Device - Xiaomi Mi 10 Lite 5G
Android version - 11
Rom - CrDroid

I've followed the install instructions, everything is functional but bluetooth and alarm audio refuses to play. On bluetooth on top if you change the output device it always takes the phone, regardless of it being a bluetooth device or not.
I've built the module according to instructions but can't replicate earlier errors (codes varied a lot) I had on Sound Model compatible. I do however get currently result code -8880 while it stating being compatible.

**Comment by KieronQuinn** [comment]
Please provide a log dump so I can see if the sound trigger platform file is doing something weird

**Comment by TheBluekr** [comment]
https://drive.google.com/file/d/18L5YJ5Y89iw33wYuxUrYbkgSBd2Pa2LX/view?usp=sharing
Hopefully logcat until this point provides enough.

**Comment by KieronQuinn** [comment]
A logcat isn't enough, the log dump contains the XML needed.

**Comment by TheBluekr** [comment]
My bad, here the log dump.
https://drive.google.com/file/d/1vI35vxx0h78cMusinrlk9cX1qd1aFzOD/view?usp=sharing

**Comment by KieronQuinn** [comment]
Thanks. Can't see anything unusual in the dump so have requested access to the full log as well. Make sure you only give access to me rather than make it public though - a full logcat can contain sensitive information.

**Comment by TheBluekr** [comment]
Granted access, made logcat for that reason private.

**Comment by KieronQuinn** [comment]
Can't see anything of use in there either, sorry. It's likely that the feature simply isn't compatible with your device and is interacting badly with something, which isn't something I can fix.
