### ISSUE TITLE
Now Playing Error

### ISSUE THREAD

**Issue by ItsMeJM** [KieronQuinn/AmbientMusicMod#161]
It says it might be outdated or incompatible with the version of ambient music mod app. It is all up to date on the update section. Have tried reinstalling both apps

**Comment by KieronQuinn** [comment]
What device / Android version?

**Comment by ItsMeJM** [comment]
Tecno LF7/ Android 12

**Comment by ItsMeJM** [comment]
Shoot it's now showing, I think it only had to download all the songs (thing) but yea it's working now. Thanks for the help
