### ISSUE TITLE
I've been having trouble keeping ambient music mod on. It turns off randomly, is this to do with debugging?

### ISSUE THREAD

**Issue by NAussieMC** [KieronQuinn/AmbientMusicMod#162]

**Comment by KieronQuinn** [comment]
When you say it turns off, do you mean Shizuku does?

**Comment by NAussieMC** [comment]
> When you say it turns off, do you mean Shizuku does?

Yes

**Comment by KieronQuinn** [comment]
Not an Ambient Music Mod issue then.

https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops
