### ISSUE TITLE
Bad sound Quality although using alternate Encoding

### ISSUE THREAD

**Issue by Vcele** [KieronQuinn/AmbientMusicMod#163]
As mentioned in the FAQ I have activated the alternative encoding setting after the sound was distorted. Now in good sound conditions my device is able to recognize songs but in most other where my recorder achieves good recordings of the song, (whatever gain I use) the sound is really recorded is really low quality and noise seems to be amplified so that the song isn't recognized. I use a OnePlus 7 pro with Pixel Experience.

**Comment by KieronQuinn** [comment]
This is normal, it uses a low quality recording and the assistant mic. It does not impact recognition, in fact the models are designed to work best like this.
