### ISSUE TITLE
App don't receive sound

### ISSUE THREAD

**Issue by matto-white** [KieronQuinn/AmbientMusicMod#165]
Phone: Xiaomi 11T pro
Miui 13 android 12
Magisk 25.2
Zygisk SUI module (latest)

The app don't recognize any song (maybe because I can't download the database) and when I listen to the playback i hear only noise. I even tried with Shizuku, same problem.

**Comment by KieronQuinn** [comment]
Enable alternative encoding in the advanced settings, like it tells you to do.
