### ISSUE TITLE
Now Playing doesn't show on lock screen

### ISSUE THREAD

**Issue by TheGreenOak** [KieronQuinn/AmbientMusicMod#166]
I'm using S23 Ultra (not rooted) One UI 5.1 April 1st version.
I've tried everything and Now Playing doesn't show on the lock screen. Any idea how to make it work?

**Comment by KieronQuinn** [comment]
Have you got Adaptive Lock Screen Overlay enabled? You may need to disable it on that device.

**Comment by TheGreenOak** [comment]
Adaptive Lock Screen Overlay is disabled, tried toggling it on and off and it did nothing.

**Comment by HaleTom** [comment]
Same issue on MIUI 13.0.10 on Xiaomi 10T Pro.  Thanks for raising @TheGreenOak

**Comment by mjain234** [comment]
Same is happening with me. You can see [here](https://imgur.com/a/rQOsr30). Don't know how it suddenly stopped working.

**Comment by KieronQuinn** [comment]
I improved the lock screen detection logic in 2.2, which should hopefully fix this. I'm also suspicious that it might be related to #157, potentially the Accessibility Service might not be enabled as it should be. 

After updating, enable the Lock Screen option, disable Adaptive Lock Screen Overlay and see if it works. If it does not, enable the Verbose Logging option in Settings > Advanced and verify that the SystemUI Package that is now listed on the Lock Screen settings page matches that for your device (some OEMs use custom ones). If it does, unfortunately I don't think there's anything I can do. If it does not, let me know and I'll reopen.

**Comment by mjain234** [comment]
Does now playing disappear from lock screen if there is no wifi/data connection? And comes back if detects any wifi/data connection? As you can see [here](https://i.imgur.com/2yPawI5.mp4) now playing wasn't here on lock screen because I have switched off my wifi and data before, then after switching wifi/data on, now playing still doesn't come back. I have to disable and then enable the accessibility to show it back on the lock screen.

**Comment by KieronQuinn** [comment]
> Does now playing disappear from lock screen if there is no wifi/data connection? And comes back if detects any wifi/data connection? As you can see [here](https://i.imgur.com/2yPawI5.mp4) now playing wasn't here on lock screen because I have switched off my wifi and data before, then after switching wifi/data on, now playing still doesn't come back. I have to disable and then enable the accessibility to show it back on the lock screen.

Your video shows it on the lock screen both before and after you disable/re-enable accessibility.
