### ISSUE TITLE
GitHub tag confusing in-app updater

### ISSUE THREAD

**Issue by Mikrz** [KieronQuinn/AmbientMusicMod#171]
It looks like the GitHub tag is set to "220" instead of "2.2.0" unlike previous releases, causing the app to think it's out of date. See below screenshot:

![Screenshot_20230418_194500_Ambient Music Mod.png](https://user-images.githubusercontent.com/767190/232928374-e011d25f-434a-47d3-a688-e64dc419fccc.png)

**Comment by KieronQuinn** [comment]
Oops, forgot I was using tags not version codes on this one. Fixed.

**Comment by Mikrz** [comment]
> Oops, forgot I was using tags not version codes on this one. Fixed.

Can confirm, that fixed it for Ambient Music Mod.

Could be a cache thing (though the AmbientMusicMod updater entry refreshed immediately) but the Now Playing updater entry isn't recognizing that it is out of date. I can probably manually update it without issue, but figured I should mention that to you as well.

Alternatively, perhaps it relies on the music db in which case I just haven't waited long enough. 😉

**Comment by KieronQuinn** [comment]
Clear the cache of Ambient Music Mod, that unclogs it. Not sure why it was doing it in the first place, swipe refreshing is supposed to ignore the cache.

**Comment by Mikrz** [comment]
Yeah, actually oddly enough Now Playing registers as being out-of-date when manually updated to 1.2, showing 1.1.1 as the newer version... 🤔

![Screenshot_20230418_200440_Ambient Music Mod.png](https://user-images.githubusercontent.com/767190/232930460-804313f2-01f9-4626-80b4-893dfbc1ec75.png)

**Comment by Mikrz** [comment]
Huh, clearing cache fixed that. Very odd behaviour.

**Comment by KieronQuinn** [comment]
Found it, [this line](https://github.com/KieronQuinn/AmbientMusicMod/blob/3703e0a17a7a16f8e55a83bad960382ff1b0fc91/app/src/main/java/com/kieronquinn/app/ambientmusicmod/ui/screens/updates/UpdatesViewModel.kt#L135) is misbehaving and telling it to skip the local version rather than the cache. Damned default arguments.

Will push a .1 release fixing that and suppressing the widget crash issue that was opened right as I was uploading

**Comment by Mikrz** [comment]
Thanks for your quick work! 😁 I use this app all the time so it's awesome to see such rapid work, even for an issue that's so easy to work around such as this (less so the widget issue I guess though, hah).
