### ISSUE TITLE
Now Playing not working 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#177]
I tried to recognise the song on lock screen through Now playing overlay but when clicking on it, nothing is happening. It used to display "Searching for track" , but [here](https://i.imgur.com/z2qo5r1.mp4) seems to happen nothing after giving a long try but clicking through widget or inside the app is working fine.

**Comment by KieronQuinn** [comment]
Do a recognition in the app from the recognise button, the widget and lock screen do not show all the error states.

**Comment by mjain234** [comment]
Yup, the same is working for me, it's able to recognise song properly and obviously the sound isn't distorted.

**Comment by mjain234** [comment]
Suddenly, now playing started to recognise the song whenever clicking on it. Don't know how it worked but there are still other things which sometimes works and sometimes doesn't like recognising song on background, showing Now Playing on lockscreen.

**Comment by mjain234** [comment]
Suddenly, now playing started to recognise the song whenever clicking on it. Don't know how it worked but there are still other things which sometimes works and sometimes doesn't like recognising song on background, showing Now Playing on lockscreen.

**Comment by mjain234** [comment]
Ok, so now again, now playing stopped working to recognise song on lockscreen but I recognise the song from inside the app, and it totally works fine, see [here](https://i.imgur.com/IhHEiTA.mp4)

**Comment by KieronQuinn** [comment]
> Ok, so now again, now playing stopped working to recognise song on lockscreen but I recognise the song from inside the app, and it totally works fine, see [here](https://i.imgur.com/IhHEiTA.mp4)

Your video shows trying to use On Demand on the lock screen (which isn't working) and then On Device in the app (which does). Please make a video using On Demand in the app when this issue happens.

**Comment by mjain234** [comment]
> > Ok, so now again, now playing stopped working to recognise song on lockscreen but I recognise the song from inside the app, and it totally works fine, see [here](https://i.imgur.com/IhHEiTA.mp4)
> 
> Your video shows trying to use On Demand on the lock screen (which isn't working) and then On Device in the app (which does). Please make a video using On Demand in the app when this issue happens.  

You mean to say, click ![this](https://user-images.githubusercontent.com/70900505/233801569-450e0536-7af0-4b7c-a462-1025970c34a0.jpg) this?

**Comment by KieronQuinn** [comment]
Yes.

**Comment by KieronQuinn** [comment]
Assuming working due to no response.

**Comment by mjain234** [comment]
> Assuming working due to no response. 

Sometimes I am facing this ![issue](https://user-images.githubusercontent.com/70900505/235438492-452d45a0-8363-4e78-826a-81ac32eed7ac.png), and then i have to disable and then enable accessibility of ambient music mod to work.

**Comment by KieronQuinn** [comment]
Nothing I can do about that, Accessibility Services do not require a token to add windows. System issue.
