### ISSUE TITLE
'An App Is Using Device Audio' Always Shows

### ISSUE THREAD

**Issue by R2-iDiot2** [KieronQuinn/AmbientMusicMod#178]
It just keeps showing
I've checked multiple times and restarted and reinstalled shizuku multiple times but it keeps showing
I've also reinstalled AMM once
I'm not very savvy in this area so pls help
![Uploading Screenshot_2023-04-24-12-08-39-097_com.kieronquinn.app.ambientmusicmod.jpg…]()

**Comment by R2-iDiot2** [comment]
Also OS is MIUI 13.0.7 (Android 12)

**Comment by KieronQuinn** [comment]
The audio playing check comes from the system, and is the same source used by Now Playing itself. If audio is playing, Now Playing may not work, so the message is shown. Not a bug.

**Comment by maozdemir** [comment]
Same issue here, probably about MIUI. This bullshit renders the entire functionality unusable.
