### ISSUE TITLE
Now Playing not working

### ISSUE THREAD

**Issue by Dragvice321** [KieronQuinn/AmbientMusicMod#179]
![Screenshot_20230428-224125.jpg](https://user-images.githubusercontent.com/131808974/235221250-12f8c057-eeac-406a-a9a8-c05a116352da.jpg)

**Comment by KieronQuinn** [comment]
Uninstall both Now Playing and Ambient Music Mod and reinstall. If that doesn't fix it, nothing I can do - this is caused by permissions issues on the system level.

**Comment by NacreousDawn596** [comment]
sorry, I didn't pay attention this issue already exists, however may I know what are the permissions required? maybe we can find a fix for rooted androids

**Comment by KieronQuinn** [comment]
Please read the linked issue, it explains what you should do.
