### ISSUE TITLE
Sound model Incompatible issue POCO F1

### ISSUE THREAD

**Issue by StarvingCyanide** [KieronQuinn/AmbientMusicMod#18]
I don't have any sound modules active whatsoever, magisk and edxposed working fine but still can't get it fixed on my POCO F1. I tried it on pixel experience rom and other roms as well but still showing the same message!!

**Comment by KieronQuinn** [comment]
Please read the compatibility page, the sound model being incompatible cannot be fixed by changing ROMs.
