### ISSUE TITLE
Wrong possition

### ISSUE THREAD

**Issue by BorjaJajas** [KieronQuinn/AmbientMusicMod#183]
![Screenshot_20230602-112811_Telegram](https://github.com/KieronQuinn/AmbientMusicMod/assets/60021453/6b2fb8cc-9071-4a61-ac02-5d78805409d3)
Look, the notification is showing in the middle of the screen but I want it in the pottom. Any solution?

**Comment by KieronQuinn** [comment]
You use the "Change Position" option which is meant for this.
