### ISSUE TITLE
On-demand/Online returns Recognition Failed

### ISSUE THREAD

**Issue by JadenJSJ** [KieronQuinn/AmbientMusicMod#184]
The Google app (not apart of the ambient music mod) can do on demand sound search, that means that It can record audio just fine)
On device recognition works just fine
On demand/Online fails and returns:
<img src="https://github.com/KieronQuinn/AmbientMusicMod/assets/44781632/9bc832c0-1dc7-40ce-916d-0167fcad97bc" width="200">

If I just rebooted my phone and I do On demand/Online the first time, I get this:
<img src="https://github.com/KieronQuinn/AmbientMusicMod/assets/44781632/8dec4f0c-546d-474b-9d55-d6aa3e07d038" width="200">

Video:
https://github.com/KieronQuinn/AmbientMusicMod/assets/44781632/ecf306ae-f41d-4d70-b35b-99822fc3ab4c

If any other additional information is needed please comment, thanks for reading.

**Comment by JadenJSJ** [comment]
![Screenshot_20230605-183219_Ambient Music Mod.png](https://github.com/KieronQuinn/AmbientMusicMod/assets/44781632/1b6abf9f-3bc1-44ba-a6db-9af059e102bd)

Sometimes I get this error instead

**Comment by KieronQuinn** [comment]
Please enable Verbose Logging in Settings > Advanced, reboot, make a log when it's running a recognition and send that.

**Comment by JadenJSJ** [comment]
![image](https://github.com/KieronQuinn/AmbientMusicMod/assets/44781632/4efe0131-0797-4250-b533-f181423b2519)
https://drive.google.com/file/d/1ZvGVuEThGkeTWVuRzZxEUMt3GspGclxp/view?usp=sharing

**Comment by JadenJSJ** [comment]
@KieronQuinn My device is rooted, is there something that could be doneby root?
I don't know much about how this works but if it was a permission error can't it just be changed?
Or is it like google app access a non-existent microphone?
