### ISSUE TITLE
[Wiki] Mention SAI

### ISSUE THREAD

**Issue by Darukutsu** [KieronQuinn/AmbientMusicMod#186]
I don't have ability to download from GooglePlayStore. AFAIK **appmirror installer** isn't on fdroid. Please mention [SAI](https://github.com/Aefyr/SAI).

![SAI](https://github.com/KieronQuinn/AmbientMusicMod/assets/54768193/5ba53adf-081e-4090-b7ed-dcb85f675ecd)

**Comment by KieronQuinn** [comment]
Done
