### ISSUE TITLE
Suggestion: Have the ongoing notification do something if the app stops "listening."

### ISSUE THREAD

**Issue by icantremember** [KieronQuinn/AmbientMusicMod#187]
I installed the mod and Shizuku on my OnePlus 11 a few days ago and just now for the second or third time, I've checked my Now Playing History to see nothing new, and then checked the Ambient Music app to see if it's listening and it's not, though the ongoing notification is still present.

I believe it dies due to the Shizuku wireless abd connection dying/getting killed (and maybe that's a OnePlus thing). BUT... it would be great if (since the Ambient app is still in the background via the ongoing notification) there could be some notification that listening has stopped.

Additional suggestion: tapping the ongoing notification could optionally open the Ambient app or the Now Playing History.

Glad to help with any testing if possible.

Thanks!

**Comment by KieronQuinn** [comment]
Which notification? The on demand one?

**Comment by icantremember** [comment]
Sorry for the delay....

This nofitication:
![image](https://github.com/KieronQuinn/AmbientMusicMod/assets/7978078/2fdf1fc2-1c6c-4de3-b5d9-bca3032ef7d5)

Another situation where it would be helpful to nofity the user that Ambient is running but not properly listening: After reboot, where Shizuku probably hasn't been manually started and Ambient can't listen but is running. The silent notification looks exactly the same whether Ambient is listening or not.

Thanks!

**Comment by KieronQuinn** [comment]
That notification is designed to be hidden, Android requires apps using foreground services to show a notification. That's why it says to hide it. 

As for the reminder, it's not really the responsibility of this app to remind you to start Shizuku, but I might add something in the future.

**Comment by icantremember** [comment]
I'm not suggesting that Ambient explicitly remind me to start Shizuku, but it would be useful to notify me somehow if the app is running and set to listen but not actually able to listen.

Thanks again.

**Comment by KieronQuinn** [comment]
That would happen every single time the device plays audio, records audio, is on a call, has battery saver enabled, etc., it would be _very_ annoying

**Comment by icantremember** [comment]
okok... just making suggestions here :)

excellent app, keep up the great work
