### ISSUE TITLE
It says "recognition requires root"

### ISSUE THREAD

**Issue by dainvincible1** [KieronQuinn/AmbientMusicMod#188]
i was unable to use the app as it says that my device need root permission. im using android 10
![Screenshot_2023-06-25-11-55-15-28_432e703e4eb809fda47320666283546a](https://github.com/KieronQuinn/AmbientMusicMod/assets/127825700/a3746d63-b66d-4598-97fd-65d1467c12a2)

**Comment by KieronQuinn** [comment]
Well, are you rooted?

**Comment by dainvincible1** [comment]
> Well, are you rooted?
no its not rooted. 
it worked without root in a different phone. maybe the issue is with my phone, im not sure

**Comment by dainvincible1** [comment]
> Well, are you rooted?

no its not rooted. 
it worked without root in a different phone. maybe the issue is with my phone, im not sure

**Comment by KieronQuinn** [comment]
It needs root on that phone. That is what it is telling you in the screenshot. Please read the FAQ next time.
