### ISSUE TITLE
Playback from history

### ISSUE THREAD

**Issue by PeteS4** [KieronQuinn/AmbientMusicMod#189]
Sorry in advance if this is already answered elsewhere, but I couldn't find anything. When I click on a song in the playback history, the only offered option is to share a google search link. If I understand issue #135 correctly it should be somehow possible to play the recognized song? If I use the manual recognition the song can for example be opened in Spotify, which would be ideal for me to also have in the history. Am I doing something wrong?

**Comment by KieronQuinn** [comment]
The way it works is there's links to various providers in the database. If you have the provider's app installed, and it's in the database, the option will appear. If it's not there, then it's not in the database. Nothing I can do about that.

**Comment by PeteS4** [comment]
Ah, thanks for the hint. I now tested all ~500 identified songs and 3 of them actually had the Spotify option. Is that an expected quote?

**Comment by KieronQuinn** [comment]
Almost all of mine on the UK database have it, but it depends which database you're using. Either way though, if it's working for _one_, that means it's working as intended. The History screen is not from the mod anyway, that's pure Google.
