### ISSUE TITLE
Adaptive notifications not working after enabling mod

### ISSUE THREAD

**Issue by duramato** [KieronQuinn/AmbientMusicMod#19]
It seems that after enabling this module adaptive notifications stops working?
It's even gone from the settings within android: [Screenshoot](https://dl3.pushbulletusercontent.com/HUEg76Wqw3fMX2oNHb454I1m6OTpLyWe/temp.jpg)

Not sure of what other info I can provide regarding this and if there's any one else experiencing this.

OnePlus 8 on Android 11
Mod: 1.1.1

**Comment by KieronQuinn** [comment]
As far as I can tell, nothing has changed. Notification suggestions still work, and that's as much as has ever done on my device.

If you had different options, disable the module and see if they return. If they don't, it's something else.

The setting is the same as before and the mod does not mess with that part of Device Personalization Services (if it exists - DPS doesn't even support providing adaptive notifications on OnePlus devices, it's handled by the default Android one, so the code simply isn't there).

For what it's worth, the options on that screenshot are identical to on my Pixel, without the mod installed. DPS doesn't support it on that device either.

**Comment by duramato** [comment]
Okay, think you are right.
Selecting None as the provider of Adaptive notifications and the Android one back again has made it work again.
Sorry for having open an issue.
