### ISSUE TITLE
Now playing "Outdated"

### ISSUE THREAD

**Issue by ItzMarioPlayz12** [KieronQuinn/AmbientMusicMod#191]
I have this issue after i installed ambient music mod and now playing it says "either now playing is uninstalled or the version is not compatible with this version of ambient music mod, please install/update it from the Updates page"
![Screenshot_20230704-113826](https://github.com/KieronQuinn/AmbientMusicMod/assets/110222477/b78901c7-70cd-4358-88e7-015a56318e2d)

**Comment by KieronQuinn** [comment]
#179
