### ISSUE TITLE
[bug] Ambient Music Mod keeps stopping if enabled run on little cores 

### ISSUE THREAD

**Issue by Pulkit077** [KieronQuinn/AmbientMusicMod#193]
After updating to the July security patch (AOSP - LineageOS & ASI version - `T.28.playstore.pixel5.542207900`) , the app is constantly crashing when the `Run on Little Cores` feature is enabled.
This feature was working fine previously, I've attached a logcat recording crash below to help debug the issue. 

https://katb.in/eqelupomine/raw

**Comment by Pulkit077** [comment]
I see `android.permission.READ_DEVICE_CONFIG` permissions denial
Correct me if I am wrong but the DeviceConfig permission is only granted to GMS app via `config_deviceConfiguratorPackageName`, isn't it?

**Comment by KieronQuinn** [comment]
You have the same issue as #146. Device config is patched out, your device isn't running the patches correctly it seems since it cannot get to that line if they were. 

If, as you say, it only happens with little cores enabled, disable the option. It's negligible in terms of battery usage anyway.
