### ISSUE TITLE
App crash after select country

### ISSUE THREAD

**Issue by NhProGamer** [KieronQuinn/AmbientMusicMod#195]
https://bin.kv2.dev/~64c9fa28e599576ea02d7051

**Comment by KieronQuinn** [comment]
It's crashing due to not having access to its own cache directory. There's absolutely nothing I can do about that, it's the system's responsibility to handle that.

**Comment by TicTecOfficial** [comment]
I know this issue is insanely outdated but KieronQuinn redirects you to this issue there is a fix:

- Manually download Now Playing from https://github.com/KieronQuinn/NowPlaying/releases
- Install it
- enjjoooyyyyyyyyy
