### ISSUE TITLE
Provide a way to enable recognise while device is is playing 

### ISSUE THREAD

**Issue by soodsid** [KieronQuinn/AmbientMusicMod#198]
So we can recognise the song while we are playing the song from the same phone.

**Comment by meilluer** [comment]
Open app in split screen

**Comment by KieronQuinn** [comment]
I've been evaluating this and it's not really possible.

- Using the `REMOTE_SUBMIX` audio source is able to capture device internal audio, but it also stops it playing through the speakers. Not an option.
- Using the projection APIs would require either a permission dialog _every time_ it wants to record, or root. Also not an option, since AMM does not require root on Android 12+.

As far as I can tell there is no other option. The assistant mic is muted when sound is playing (which is why the app tells you another app is using device audio), so it's not as simple as just disabling the check.

**Comment by meilluer** [comment]
> I've been evaluating this and it's not really possible.
> 
> * Using the `REMOTE_SUBMIX` audio source is able to capture device internal audio, but it also stops it playing through the speakers. Not an option.
> * Using the projection APIs would require either a permission dialog _every time_ it wants to record, or root. Also not an option, since AMM does not require root on Android 12+.
> 
> As far as I can tell there is no other option. The assistant mic is muted when sound is playing (which is why the app tells you another app is using device audio), so it's not as simple as just disabling the check.

Something like this is already possible in shazam(maybe you can tray replicate it?), maybe it uses external mic from headphones as they are closer to audio source. If none of it works you be root implementation could be implemented as a root-only feature

**Comment by KieronQuinn** [comment]
> > I've been evaluating this and it's not really possible.
> > 
> > * Using the `REMOTE_SUBMIX` audio source is able to capture device internal audio, but it also stops it playing through the speakers. Not an option.
> > * Using the projection APIs would require either a permission dialog _every time_ it wants to record, or root. Also not an option, since AMM does not require root on Android 12+.
> > 
> > As far as I can tell there is no other option. The assistant mic is muted when sound is playing (which is why the app tells you another app is using device audio), so it's not as simple as just disabling the check.
> 
> Something like this is already possible in shazam(maybe you can tray replicate it?), maybe it uses external mic from headphones as they are closer to audio source. If none of it works you be root implementation could be implemented as a root-only feature

Shazam will use the projection option, it's not an option for automated recognition. I also don't want to add it as a root-only feature because the rest of the app has moved _away_ from that.

**Comment by soodsid** [comment]
I didn't knew it was possible to add a comment in the closed issue so I just created another issue about it and I also posted a solution, it's not a solution basically but it is a workaround. so if you want to you can try that

**Comment by megapro17** [comment]
why it can recognize songs on pixel when device is playing anyway?
