### ISSUE TITLE
Now playing not showing on lockscreen 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#199]
Now playing sometimes used to show on lockscreen but failed maximum times. You can see the video [here](https://imgur.com/a/jCUJodU).

**Comment by KieronQuinn** [comment]
You do not have the on demand option for showing in the lock screen overlay enabled, and there are no recognitions (none showing in the history), this is working as intended.

**Comment by mjain234** [comment]
You are mentioning about this function? ![Screenshot_20230904-111428~2.png](https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/53183f96-9c5c-4213-81c1-5c058da904d0)

**Comment by KieronQuinn** [comment]
Yes, since you have it disabled and there's no recognised song there's no overlay to show. It's working as intended.
