### ISSUE TITLE
Ruined my OnePlus 7 pro

### ISSUE THREAD

**Issue by MOOOOs** [KieronQuinn/AmbientMusicMod#20]
When installed and rebooted my op I got bootloop and now after few bootlops my lock screen not working so I can't access my phone. Please help quick

**Comment by KieronQuinn** [comment]
Boot into Magisk safe mode and uninstall the app (which will also disable the Xposed module). Disable the Magisk module too and reboot.

**Comment by MOOOOs** [comment]
Tried not working it boots up and I only can see wallpaper and screen unlock not appearing

**Comment by KieronQuinn** [comment]
If you have booted without Magisk and it's the same, there's nothing else that can be done. Restore a backup if you have one.

**Comment by MOOOOs** [comment]
Then why this module do this?

**Comment by MOOOOs** [comment]
Also what magisk safe mode you talking about

**Comment by KieronQuinn** [comment]
> Then why this module do this?

If it's still not working after removing the Xposed module, it may be a permissions issue. This is always a risk when using modules that add priv-app permissions. The solution is to restore a backup, or to reset.

**Comment by KieronQuinn** [comment]
> Also what magisk safe mode you talking about

https://topjohnwu.github.io/Magisk/faq.html

**Comment by marie6324** [comment]
I've unfortunately been able to replicate this. It left my phone getting past the boot animation and going straight to a black screen. Magisk was thrown into core mode (and then disabled), app removal was attempted via the file system. The phone was left entirely unresponsive.

**Comment by KieronQuinn** [comment]
> If it's still not working after removing the Xposed module, it may be a permissions issue. This is always a risk when using modules that add priv-app permissions. The solution is to restore a backup, or to reset.
