### ISSUE TITLE
On demand service not available

### ISSUE THREAD

**Issue by Lelonio** [KieronQuinn/AmbientMusicMod#200]
Since my firmware is compatible with on demand recognition, i've installed the correct google app version but then got this error

![Screenshot_20230907-110919_Ambient Music Mod](https://github.com/KieronQuinn/AmbientMusicMod/assets/21023829/ed2b30e1-fddb-4b56-8224-ad6a8a6d6ac6)

**Comment by KieronQuinn** [comment]
This error comes direct from the framework and is not under AMM control. If it says it's not available, it's not available.

**Comment by Lelonio** [comment]
> This error comes direct from the framework and is not under AMM control. If it says it's not available, it's not available.

So is there something the rom's dev can do?

**Comment by KieronQuinn** [comment]
It's usually caused by an incompatibility in the Google app so unlikely

**Comment by Lelonio** [comment]
> It's usually caused by an incompatibility in the Google app so unlikely

Are you suggesting to download another version?

**Comment by KieronQuinn** [comment]
No, I'm saying there probably is no fix.
