### ISSUE TITLE
External Access not working 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#201]
As I tried to use this External Access function, I am facing this [issue](https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/ec5dc2bd-7e43-4c0c-827f-b03a5fa51751
). I read whole wiki of how to use it but still not working for me. Am i doing something wrong here?

**Comment by mjain234** [comment]
Yup, that's what the problem I have faced, it doesn't work with External Access but when click on Device Recognition through widget, it works. https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/843e80bb-f5a3-4146-b19f-494e74614767

**Comment by KieronQuinn** [comment]
Running recognition via Tasker does not trigger the widget, this is how it is intended. Enable verbose logging and check the log, it should show 

`I AmbientMusicDetector: Running on-device song recognition.`

**Comment by KieronQuinn** [comment]
https://www.xda-developers.com/how-to-take-logs-android/

System log will show it.

**Comment by mjain234** [comment]
Yaa, I just saw the [log](https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/e3a90fdb-78fc-454d-8780-09e6fbf02559) and it is showing what you told but when I try to recognise through Tasker, i don't know how much time it takes but through widget it recognises fast as you can see [here](https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/3611b953-3490-4cc5-b34b-412665f9159d)

**Comment by KieronQuinn** [comment]
It's working fine then.
