### ISSUE TITLE
Not downloading songs database

### ISSUE THREAD

**Issue by adiluzzaman824** [KieronQuinn/AmbientMusicMod#205]
![Screenshot_2023-09-21-19-50-02-549_com kieronquinn app ambientmusicmod](https://github.com/KieronQuinn/AmbientMusicMod/assets/105024583/514510ef-0278-4c12-87d3-c5ff3b6f86be)
![Screenshot_2023-09-21-19-43-18-538_com kieronquinn app ambientmusicmod](https://github.com/KieronQuinn/AmbientMusicMod/assets/105024583/9754c775-3e6c-4df5-80d2-16c2200900b4)

**Comment by adiluzzaman824** [comment]
It's not downloading

**Comment by KieronQuinn** [comment]
#173
