### ISSUE TITLE
Android 9: “Now Playing keeps stopping” error keeps popping up.

### ISSUE THREAD

**Issue by TicTecOfficial** [KieronQuinn/AmbientMusicMod#207]
Device: Samsung S8
Android Version: Android 9
Root: Yes.

![image](https://github.com/KieronQuinn/AmbientMusicMod/assets/97348600/e733e9a5-ead0-47f8-9008-992aa71b71af)

**Comment by KieronQuinn** [comment]
Please provide a logcat.

**Comment by TicTecOfficial** [comment]
[Uploading alogcat.2023-10-01-07-39-26+0800.txt…]()

**Comment by TicTecOfficial** [comment]
[alogcat.2023-10-01-07-39-26+0800.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/12775735/alogcat.2023-10-01-07-39-26%2B0800.txt)

**Comment by KieronQuinn** [comment]
#146
