### ISSUE TITLE
Trigger Google Assistant via Ambient Music Mod

### ISSUE THREAD

**Issue by cy4njk** [KieronQuinn/AmbientMusicMod#209]
Would it be possible to use the Ambient Music Mod platform to get it to recognize a user-defined hotword and trigger google assistant?

I guess it would require upping the frequency with which AMM takes audio samples, which would in turn increase battery drain, but maybe a workaround could be found. Just an idea though.

**Comment by KieronQuinn** [comment]
No, the hotword bit (using the hotword engine to detect when sound is playing) is disabled in AMM because it's almost impossible to port.
