### ISSUE TITLE
[bug] ambient music fails to start

### ISSUE THREAD

**Issue by mackdroid** [KieronQuinn/AmbientMusicMod#21]
Handset:- redmi note 9 pro miatoll
I use a los fork called sakura project with Nik gapps ![Screenshot_20210428-111653_Ambient_Music_Mod.png](https://user-images.githubusercontent.com/68280146/116352729-3f9c8780-a813-11eb-8abe-8a686fe7c1f4.png)
Logs http://0x0.st/-mRN.zip

**Comment by mackdroid** [comment]
```04-28 11:21:51.597 27241 27241 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:21:56.635 27266 27266 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:22:01.640 27274 27274 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:22:06.663 27276 27276 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:22:11.682 27291 27291 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:22:16.693 27298 27298 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:22:21.719 27312 27312 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...
04-28 11:22:26.730 27335 27335 F linker  : CANNOT LINK EXECUTABLE "/system/product/bin/dpmd": cannot locate symbol "strdup8to16" referenced by "/product/lib64/libdpmframework.so"...```
I get this in edxposed logs whenever I run test recognition

**Comment by KieronQuinn** [comment]
Please provide a log dump. However, if EdXposed isn't working at all this mod will obviously not work either and you should look at fixing that first before complaining that this doesn't work.

**Comment by karolpeszek** [comment]
I have the same issue. It seems like Pixel Ambient Services get stopped in the background. Here is my logcat.
[logcat.log](https://github.com/KieronQuinn/AmbientMusicMod/files/6590105/logcat.log)

**Comment by KieronQuinn** [comment]
> I have the same issue. It seems like Pixel Ambient Services get stopped in the background. Here is my logcat.
> [logcat.log](https://github.com/KieronQuinn/AmbientMusicMod/files/6590105/logcat.log)

`V SoundTriggerService: 9f6ad62a-1f0b-11e7-87c5-40a8f03d3f15: onError: -2147483648`

There's no known fix for this.
