### ISSUE TITLE
song recognition only

### ISSUE THREAD

**Issue by appleboblin** [KieronQuinn/AmbientMusicMod#210]
Hi, 
I'm currently running GrapheneOS on my Pixel 8. I'm wondering if its possible to only use the song recognition function with offline database like a regular application? I do not want my mic to be constantly listening to audio, something like Shazam where it only works when I press a button in an application. 
Sorry for continence if this is not the right place to ask this question.

**Comment by appleboblin** [comment]
After playing around, seems like I can set the recognition period to never, I'm wondering if this method still requires shizuku? would be nice if it doesn't require shizuku for manual trigger

**Comment by KieronQuinn** [comment]
Offline recognition only is the default. Manual recognition is as you have discovered the same as what Shazam does, but the recognition never leaves your device - automatic recognition is the same, but runs automatically periodically. Either way, your mic will only be used for local recognition and audio is never sent to a server.

The only time server-based recognition is used is when On Demand is used, which requires the Google app. Given you're using GrapheneOS, I presume you are using a de-googled installation, so On Demand would not work on your device anyway.

Shizuku is required for the app to function at all, it is a requirement for recording audio not for running in the background.
