### ISSUE TITLE
[REQUEST] Z Flip5 Cover Screen

### ISSUE THREAD

**Issue by LetGoMylegos** [KieronQuinn/AmbientMusicMod#212]
Hi, I was just wondering if there are plans to make the ambient music notification show on the Z Flip5's cover screen. Thank you!

**Comment by KieronQuinn** [comment]
Is that one of the ones that supports custom widgets on the cover screen or is it just an always on display?

**Comment by LetGoMylegos** [comment]
> Is that one of the ones that supports custom widgets on the cover screen or is it just an always on display?

The Z Flip5 has both but I think putting it on the AOD would be a lot harder

**Comment by KieronQuinn** [comment]
I can probably make the Ambient Music Mod widget be an option for the cover screen, though in the meantime it's possible already using [Smartspacer](https://github.com/KieronQuinn/Smartspacer), whose widget already works on the cover screen and can show Ambient Music Mod.

**Comment by LetGoMylegos** [comment]
> I can probably make the Ambient Music Mod widget be an option for the cover screen, though in the meantime it's possible already using [Smartspacer](https://github.com/KieronQuinn/Smartspacer), whose widget already works on the cover screen and can show Ambient Music Mod.

Hey, I'm probably just dumb but I can't figure out how to get it as a cover screen widget. It seems to be a inside screen widget only.

**Comment by KieronQuinn** [comment]
> > I can probably make the Ambient Music Mod widget be an option for the cover screen, though in the meantime it's possible already using [Smartspacer](https://github.com/KieronQuinn/Smartspacer), whose widget already works on the cover screen and can show Ambient Music Mod.
> 
> Hey, I'm probably just dumb but I can't figure out how to get it as a cover screen widget. It seems to be a inside screen widget only.

Smartspacer has the config which _should_ allow it (Ambient Music Mod does not), but I don't have a device to test on. If it doesn't work, not a lot I can do unfortunately.

**Comment by LetGoMylegos** [comment]
> > > I can probably make the Ambient Music Mod widget be an option for the cover screen, though in the meantime it's possible already using [Smartspacer](https://github.com/KieronQuinn/Smartspacer), whose widget already works on the cover screen and can show Ambient Music Mod.
> > 
> > Hey, I'm probably just dumb but I can't figure out how to get it as a cover screen widget. It seems to be a inside screen widget only.
> 
> Smartspacer has the config which _should_ allow it (Ambient Music Mod does not), but I don't have a device to test on. If it doesn't work, not a lot I can do unfortunately. 

I still can't figure out Smartspacer, but it's not that big of a deal. Thank you anyways!

**Comment by KieronQuinn** [comment]
2.3.2 now includes the same XML as Smartspacer so should display on the flip's outer screen

**Comment by LetGoMylegos** [comment]
The Z Flip still can't have ordinary home screen widgets sadly. The only way it could work is if it displays on the cover lock screen like the inner screen does.

**Comment by KieronQuinn** [comment]
The XML already included is the only known way to make it appear unfortunately, there's nothing more I can do.

**Comment by LetGoMylegos** [comment]
Can't you just have it appear on top of the Cover Screen's lock screen like it does on the main screen?
