### ISSUE TITLE
app still asking for updates even though it's up-to-date.

### ISSUE THREAD

**Issue by NacreousDawn596** [KieronQuinn/AmbientMusicMod#215]
![Screenshot_20231207-162337](https://github.com/KieronQuinn/AmbientMusicMod/assets/75474839/17efdd8f-2d3f-4eff-8e67-72f1cdc27340)
![Screenshot_20231207-162343](https://github.com/KieronQuinn/AmbientMusicMod/assets/75474839/ef4d555d-343e-44e7-b9e9-62de201b6cf1)
as the title says

**Comment by KieronQuinn** [comment]
#179
