### ISSUE TITLE
[bug] lockscreen overlay not showing result if trigger is used.

### ISSUE THREAD

**Issue by jafri-jahan-s** [KieronQuinn/AmbientMusicMod#216]
The lockscreen overlay is not showing the result if I use an external trigger to recognise. Also the inbuilt trigger "screen on" is not working hence the need to implement external trigger. The external trigger works since "now Playing" gives notification of the result but is not displaying in lockscreen. 

External trigger - used macrodroid, trigger- screen on
Device- OnePlus 7 pro, custom rom (pixel experience 14)

Thanks.

**Comment by KieronQuinn** [comment]
Both fixed in 2.3.2
