### ISSUE TITLE
Ambient Music Mod doesn't work on Samsung Galaxy A34 5G

### ISSUE THREAD

**Issue by k3rnelpanik** [KieronQuinn/AmbientMusicMod#217]
I'm trying to get AMM to work on the Samsung Galaxy A34 5G, but it keeps failing to work.
I have set up the app, as well as shizuku, but for some reason, whenever I try to recognise any playing music, AMM tells me that "recognition failed" due to it getting "timed out for response".
Upon closer inspection, I found that the Now Playing app keeps crashing over and over again. Is this a known issue, if so, how could I fix this.

Device: Samsung Galaxy A34 5G
OneUI 6.0 based on Android 14 (The issue also persisted with OneUI 5.1 @ Android 13).

**Comment by KieronQuinn** [comment]
Please provide a logcat.

**Comment by k3rnelpanik** [comment]
> Please provide a logcat.

[log.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/13647386/log.txt)

**Comment by KieronQuinn** [comment]
Unfortunately that's a native crash, which in Now Playing is beyond my control. There's nothing I can do.
