### ISSUE TITLE
[Request] Lockscreen display when listening

### ISSUE THREAD

**Issue by SDBdevelopment** [KieronQuinn/AmbientMusicMod#218]
Hi Kieron,

First, thank you for the great piece of software!
Would it be possible to show the song identified icon (without a title) on the lockscreen when the app is still listening?
Like it works on the Pixel ?

Thank you!

Simon

**Comment by KieronQuinn** [comment]
Not sure what you mean, the Pixel doesn't show anything when it's listening (because it's always listening), do you have an example screenshot

**Comment by SDBdevelopment** [comment]
Hi Kieron,

Thank you for you reaction. 

I'm currently not on the Pixel (OS) to make a screenshot for you. I'f found an example screenshot.
![image](https://github.com/KieronQuinn/AmbientMusicMod/assets/18560182/a47d5f55-c425-4dab-b1cd-1f110ac74451)
When sound (i think) is detected it will show 'Searching for song...'.
With newest 'Now playing' version the song icon is also showing and not recogizing the song and it lets you connect online to improve the detection.

**Comment by KieronQuinn** [comment]
That's On Demand, it's already in the app.
