### ISSUE TITLE
Now Playing Crashes

### ISSUE THREAD

**Issue by chanobraichseo** [KieronQuinn/AmbientMusicMod#219]
https://paste.evolution-x.org/GYxMSa

I installed and configured Now Playing through Ambient Music Mod, and even though it recognizes songs, there comes a time where the app crashes..

Before submitting the issue, I decided to check the logs a little, it turns out that Now Playing crashes because it does not have permissions to read configs, (To check if screen is on) so I decided to give it permissions with adb from my Laptop (Obvious disclaimer: Having periodic detection activated, I have activated the option to recognize songs every time the screen turns on, I saw it more convenient)
_________________________________________

so.. it turns out, that even giving it permissons, and even disabling the trigger when screen on still makes Now Playing crash...

Any help/idea yall give me?

**Comment by KieronQuinn** [comment]
#146
