### ISSUE TITLE
Xposed Module not enabled You must enable the Xposed module for Ambient Music to work

### ISSUE THREAD

**Issue by hehedemuse** [KieronQuinn/AmbientMusicMod#22]
My device is Redmi 4X, LianageOS 18.1. I have installed Edxposed, but it still shows "Xposed Module not enabled You must enable the Xposed module for Ambient Music to work"

**Comment by KieronQuinn** [comment]
Reboot, that usually fixes it. If it still doesn't, make sure Xposed is actually working on your device.

**Comment by hehedemuse** [comment]
I try to reboot, but it still doesn't work.
And Xposed is actually working.

**Comment by hehedemuse** [comment]
![Uploading Screenshot_20210503-093057_Pixel_Launcher.png…]()

**Comment by KieronQuinn** [comment]
That image didn't upload

**Comment by hehedemuse** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=79510b4c45&attid=0.1&permmsgid=msg-a:r-232860036922269875&th=179300f19300351b&view=fimg&realattid=1792fda1ab5d9b6115c1&disp=thd&attbid=ANGjdJ8zHCUNGU9vNv5pIxOLvkKt6mRddCPf3E95EgIqv1S3gMJnxhLKKcLjo3FDpGQonIEI_SIPy6_iz5GgG_dZCIgU2N1EAMZDvdd3ec5euuFJtQBoTnZbdNCwyuM&ats=2524608000000&sz=w960-h979

**Comment by hehedemuse** [comment]
![Uploading Screenshot_20210501-014354_Ambient_Music_Mod.jpg…]()

**Comment by hehedemuse** [comment]
![Screenshot_20210501-014354_Ambient_Music_Mod](https://user-images.githubusercontent.com/78913276/120915025-0e498e00-c6d4-11eb-84a8-77e794f81a0b.jpg)

**Comment by KieronQuinn** [comment]
Send a screenshot of the Xposed manager app on your device too please.

**Comment by hehedemuse** [comment]
The xposed module is enabled, but cannot be started
![Uploading Screenshot_20210608-072455_Ambient_Music_Mod.png…]()

**Comment by hehedemuse** [comment]
![Uploading Screenshot_20210608-072455_Ambient_Music_Mod.jpg…]()

**Comment by hehedemuse** [comment]
![Screenshot_20210608-072455_Ambient_Music_Mod](https://user-images.githubusercontent.com/78913276/121108227-f68d1980-c83b-11eb-9c74-b4ca131b4d51.jpg)
