### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by Zyo20** [KieronQuinn/AmbientMusicMod#222]
Could the widget be improved with no sharp edges just like the Google widget? 
![Screenshot_2024-01-16-23-54-57-34_b783bf344239542886fee7b48fa4b892](https://github.com/KieronQuinn/AmbientMusicMod/assets/24516479/e22812c7-37ce-4c85-a1f9-126f4c91842d)
 
![Screenshot_2024-01-16-23-56-04-83_b783bf344239542886fee7b48fa4b892](https://github.com/KieronQuinn/AmbientMusicMod/assets/24516479/8c0a994c-1c53-4920-8806-5f7bb7c92c7c)

**Comment by KieronQuinn** [comment]
It already has rounded corners on devices with support, yours does not.
