### ISSUE TITLE
[REQUEST] Show on doze mode/peek display.

### ISSUE THREAD

**Issue by shef3r** [KieronQuinn/AmbientMusicMod#223]
On some devices, there's a pixel-like "doze mode" (ex. on my motorola), which is kind of like an AOD with a dimmed wallpaper (example attached).

I wasn't sure if it would qualify under the AOD thing in the FAQ, so that's why I asked anyway.

<img src="https://github.com/KieronQuinn/AmbientMusicMod/assets/79228174/451adcc4-df7d-497d-8dff-2257ceb60314" width=300>
 
 I would like AMM to show on this screen just like on the lock screen without root, if possible.

**Comment by KieronQuinn** [comment]
It still counts.
