### ISSUE TITLE
Unable to install the database pack. 

### ISSUE THREAD

**Issue by Chaichai95** [KieronQuinn/AmbientMusicMod#227]
I proceeded to the installation of the music database. And encountered this.
![Screenshot_20240208_144524_SAI](https://github.com/KieronQuinn/AmbientMusicMod/assets/159418577/7106d450-87ef-4986-8169-45f471b88b0d)
![Screenshot_20240208_144020_SAI](https://github.com/KieronQuinn/AmbientMusicMod/assets/159418577/4b9febe2-816b-4bcc-b861-83bb8e2ebf30)

I have no knowledge on coding whatsoever. Any advice on how to solve this would greatly be appreciated. Xx

**Comment by KieronQuinn** [comment]
That's not an issue of this app.

**Comment by Chaichai95** [comment]
Thank you, but could you please point out what am I missing here.

**Comment by KieronQuinn** [comment]
It's not this app. It's an SAI issue. https://github.com/Aefyr/SAI/issues/216

**Comment by Chaichai95** [comment]
Found it. It's the issue with the installer. Thank you so much for the efforts put into this project.
