### ISSUE TITLE
Music database seems to be downloaded but displayed as not

### ISSUE THREAD

**Issue by rafalou38** [KieronQuinn/AmbientMusicMod#228]
I have had the app for a long time and a few months ago, it started a database update that would never finish (had it on Wi-Fi, charged, etc for various months, just forgot about it).
So with the `2.3.2` release (4 days) ago I tried a new clean install and as of today it still displays as downloading.
The neat part is that although it shows as downloading, it does recognize music in the background from time to time.
and btw, This time I tried to stick with the default database instead of English+French+Spanish.
ps: I got pretty fast internet (200mb/s Wi-Fi) so that's probably not the issue.

**Comment by KieronQuinn** [comment]
#173

**Comment by rafalou38** [comment]
First of all, I would like to thank you for the amazing work you do here. 
The app is really amazing and does the job perfectly well.

That being said, I know this is a known issue and I have read the issue `#173` but it ain't fixing anything.
I am patient, I already waited literally weeks and months for the database to download, restarted my phone many times, and even uninstalled and re-installed the app.
I can say with confidence that it's not something about being patient. But an issue, whether with the app or an incompatibility (which suddenly emerged from nowhere) with my phone.

It would be really nice if you could address the issue. 
I think a more verbose download status could help a lot.
Which could, for example, display the current download phase, which database is downloading, what is the download speed...
If I remember correctly, I have read in an issue that the download is made externally from the app.
It would be amazing if you could download it internally so that a real progress-bar could be shown, which wouldn't leave the users in the unknown wondering whether it's broken or just needs a little more waiting.
I don't know how it could be implemented but that would definitely be nice to have.

👍
