### ISSUE TITLE
Doesn't work with the newest google app

### ISSUE THREAD

**Issue by Areg472** [KieronQuinn/AmbientMusicMod#229]
So I have a rooted phone and I goy a google app update. I of course went to apkmirror and installed the latest version of google with the bundle ending with .29. But the ondemand feature isn't still working. Please fix it

**Comment by KieronQuinn** [comment]
Please send a link to the version on APKmirror you installed so I can test with it.

**Comment by Areg472** [comment]
https://www.apkmirror.com/apk/google-inc/google-search/google-search-15-5-58-release/google-app-15-5-58-29-arm64-android-apk-download/

**Comment by KieronQuinn** [comment]
That version does not have the sound search fingerprinter split (step 5 of the [Enabling on Demand](https://github.com/KieronQuinn/AmbientMusicMod/wiki/Enabling-On-Demand) guide). This is not a bug.
