### ISSUE TITLE
LSPosed Invisible

### ISSUE THREAD

**Issue by AvgZing** [KieronQuinn/AmbientMusicMod#23]
Ambient Music Mod does not show up in the LSPosed app list. I've enabled the module for "System Framework" and "Pixel Ambient Services" but Ambient Music Mod app is missing.

**Comment by KieronQuinn** [comment]
This is normal, EdXposed and LSposed will both enable the module on itself by default (though EdXposed shows it in the list, Lsposed apparently does not)
