### ISSUE TITLE
LOCKSCREEN DISPLAY UNAVAILABLE FOR MY DEVICE 

### ISSUE THREAD

**Issue by ThePolarOne** [KieronQuinn/AmbientMusicMod#230]
On my Nothing Phone (1) running Nothing OS 2.5.2, Android 14, the identified tracks aren't being shown on the lockscreen. The Accessibility service is apparently not available due to security concerns. Any Help? 

![Screenshot_20240210-014547](https://github.com/KieronQuinn/AmbientMusicMod/assets/142078720/f2bb79a0-4543-40a2-94dd-d31d55a7e1b3)
![Screenshot_20240210-014539](https://github.com/KieronQuinn/AmbientMusicMod/assets/142078720/0806ac8e-dde6-4320-806d-7316fe70be82)

P.S.: My device was recently updated to the said OS versions

**Comment by ThePolarOne** [comment]
P.S.: My device was recently updated to the said OS versions

**Comment by KieronQuinn** [comment]
https://support.google.com/android/answer/12623953?hl=en-GB

**Comment by ThePolarOne** [comment]
> https://support.google.com/android/answer/12623953?hl=en-GB

Thanks a lot
