### ISSUE TITLE
US music database track listing is not loaded correctly 

### ISSUE THREAD

**Issue by fg817sw751478** [KieronQuinn/AmbientMusicMod#237]
Title. I opened a song on YouTube and the notification immediately popped about that song which wasn't even in the database, then disappeared. Interesting to say the least.

Is this normal?

**Comment by KieronQuinn** [comment]
What was the song?

**Comment by ghost** [comment]
> What was the song?

, tried to search it in the database but can't find it, On Demand is not set up

**Comment by KieronQuinn** [comment]
> > What was the song?
> 
> "Up in my jam" by Kubbi, tried to search it in the database but can't find it, On Demand is not set up

I can see it in the UK database, which database are you using?

**Comment by KieronQuinn** [comment]
How many tracks are showing as in the database for you on the updates tab?

**Comment by KieronQuinn** [comment]
Yeah I thought so, that's just the core database. There's something wrong with the loading of tracks for the US one, but it's not impacting the UK one.

**Comment by KieronQuinn** [comment]
Fixed in Now Playing 1.3.5
