### ISSUE TITLE
Z Fold 5 - One UI 6.1 - Stuck on loading when opening app

### ISSUE THREAD

**Issue by escenkay** [KieronQuinn/AmbientMusicMod#239]
When I open the app, the main screen is stuck on loading. Tried to reboot and re-enable shizuku a few times but issue persists.  The updates page in the app seems to work fine.

Extracted this from matlog:

04-06 15:55:01.249 I/AppIconSolution(29283): start to load, pkg=com.kieronquinn.app.ambientmusicmod, bg=288-288, dr=296-296, forDefault=false, density=0
04-06 15:55:01.249 I/AppIconSolution(29283): scale down, pkg=com.kieronquinn.app.ambientmusicmod, dr=216-216, bg=288-288
04-06 15:55:01.249 I/AppIconSolution(29283): fromTheme, pkg=com.kieronquinn.app.ambientmusicmod, bg=288-288, dr=216-216, relScale=1.1866667, Scale = 0.89, isNight = true
04-06 15:55:01.294 I/AppIconSolution(29283): start to load, pkg=com.kieronquinn.app.ambientmusicmod, bg=288-288, dr=296-296, forDefault=false, density=0
04-06 15:55:01.294 I/AppIconSolution(29283): scale down, pkg=com.kieronquinn.app.ambientmusicmod, dr=216-216, bg=288-288
04-06 15:55:01.294 I/AppIconSolution(29283): fromTheme, pkg=com.kieronquinn.app.ambientmusicmod, bg=288-288, dr=216-216, relScale=1.1866667, Scale = 0.89, isNight = true
04-06 15:55:01.296 I/AppIconSolution(29283): start to load, pkg=com.kieronquinn.app.ambientmusicmod, bg=288-288, dr=296-296, forDefault=false, density=0
04-06 15:55:01.296 I/AppIconSolution(29283): scale down, pkg=com.kieronquinn.app.ambientmusicmod, dr=216-216, bg=288-288
04-06 15:55:01.296 I/AppIconSolution(29283): fromTheme, pkg=com.kieronquinn.app.ambientmusicmod, bg=288-288, dr=216-216, relScale=1.1866667, Scale = 0.89, isNight = true
04-06 15:55:01.327 W/ndroid.settings(29283): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~GhqgCkASyp_6EZHY1xONaA==/com.kieronquinn.app.ambientmusicmod-6xgHdxuYz3SzIr6x-Dj-oA==/base.apk' with 1 weak references
04-06 15:55:01.339 W/PackageConfigPersister(2605): App-specific configuration not found for packageName: com.kieronquinn.app.ambientmusicmod and userId: 0
04-06 15:55:01.339 I/AppButtonsPrefCtl(29283): AppButton refreshUI for Pkg : com.kieronquinn.app.ambientmusicmod
04-06 15:55:01.389 I/Role    (30373): com.kieronquinn.app.ambientmusicmod not qualified for android.app.role.HOME due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.MAIN', mCategories='[android.intent.category.HOME]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mFlags='0', mPermission='null', mQueryFlags=0, mMetaData=[]}
04-06 15:55:01.391 I/Role    (30373): com.kieronquinn.app.ambientmusicmod not qualified for android.app.role.DIALER due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.DIAL', mCategories='[]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mFlags='0', mPermission='null', mQueryFlags=0, mMetaData=[]}
04-06 15:55:01.393 I/Role    (30373): com.kieronquinn.app.ambientmusicmod not qualified for android.app.role.SMS due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.provider.Telephony.SMS_DELIVER', mCategories='[]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mFlags='0', mPermission='android.permission.BROADCAST_SMS', mQueryFlags=0, mMetaData=[]}
04-06 15:55:01.394 I/Role    (30373): com.kieronquinn.app.ambientmusicmod not qualified for android.app.role.HOME due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.MAIN', mCategories='[android.intent.category.HOME]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mFlags='0', mPermission='null', mQueryFlags=0, mMetaData=[]}
04-06 15:55:01.395 E/AppInfoDashboard(29283): Package: com.kieronquinn.app.ambientmusicmod not found for user: 150
04-06 15:55:01.579 D/AppButtonsPrefCtl(29283): Got broadcast response: Restart status for com.kieronquinn.app.ambientmusicmod true
04-06 15:55:08.229 I/HoneySpace.SuggestedItemsFacade(16095): DPS items : Ambient Music Mod, com.kieronquinn.app.ambientmusicmod/.ui.activities.MainActivity#UserHandle{0}
04-06 15:55:08.229 I/HoneySpace.SuggestedItemsFacade(16095): filteredItem : com.kieronquinn.app.ambientmusicmod/.ui.activities.MainActivity#UserHandle{0}
04-06 15:55:08.229 I/HoneySpace.SuggestedItemsFacade(16095): item removed by filter - com.kieronquinn.app.ambientmusicmod
04-06 15:55:08.245 I/HoneySpace.TaskListViewModel(16095):  Task1 : [id=3822 windowingMode=1 user=0 lastActiveTime=759893643] null, isCoverLauncherTask = false, isLocked = false - com.kieronquinn.app.ambientmusicmod]
04-06 15:55:08.265 I/HoneySpace.TaskAdapter(16095): attach [position: 1], taskData size: 44, item: ComponentInfo{com.kieronquinn.app.ambientmusicmod/com.kieronquinn.app.ambientmusicmod.ui.activities.MainActivity}, animReady: 2, firstBindingComplete: 3, view: 812aa08
04-06 15:55:08.267 I/HoneySpace.TaskDataRepositoryImpl(16095): Request icon and label, id=3822, iconAndLabel: IconAndLabel(icon=android.graphics.Bitmap@e7fcc95, label=Ambient Music Mod), componentKey: com.kieronquinn.app.ambientmusicmod/.ui.activities.MainActivity#UserHandle{0}

**Comment by KieronQuinn** [comment]
Thanks for the report, unfortunately there's nothing of use in that log. Is there anything for the other app (com.kieronquinn.app.pixelambientmusic)?

**Comment by escenkay** [comment]
[logcat.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/14899254/logcat.txt)

I pulled another one. Attaching for reference.

I filtered it using the package ID 

Thank you

**Comment by KieronQuinn** [comment]
The only bad thing I can see in there is related to widgets, which shouldn't cause this but I could be wrong. Could you try removing all Ambient Music Mod widgets from **any** home screen (not just the default one), rebooting and seeing if that fixes it?

**Comment by escenkay** [comment]
> The only bad thing I can see in there is related to widgets, which shouldn't cause this but I could be wrong. Could you try removing all Ambient Music Mod widgets from **any** home screen (not just the default one), rebooting and seeing if that fixes it? 

Removed the widget, rebooted, re-enabled shizuku and it seems to be working now.

That's strange the widget was casuing issues. 

I was using it as a stacked widget along with the Smart Spacer widget. Anyways appreciate your assistance!

**Comment by KieronQuinn** [comment]
> > The only bad thing I can see in there is related to widgets, which shouldn't cause this but I could be wrong. Could you try removing all Ambient Music Mod widgets from **any** home screen (not just the default one), rebooting and seeing if that fixes it?
> 
> Removed the widget, rebooted, re-enabled shizuku and it seems to be working now.
> 
> That's strange the widget was causing issues.
> 
> I was using it as a stacked widget along with the Smart Spacer widget. Anyways appreciate your assistance!

Thanks, the 'fix' for the widget issue (suppressing it because there's nothing else I can do) will be in the next release so will solve this too then

**Comment by KieronQuinn** [comment]
Fixed added in 2.3.5
