### ISSUE TITLE
Recognition not working 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#242]
I have my nothing phone 1 with me and updated my Google app to .29 version model to work with Ambient Music mod but when I try to play any music from device and try to recognise, but it isn't working. Tried with both Online and offline with Alternative Encoding too, still didn't work. 
https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/ca6e0b39-d1e9-4b86-8456-08bd0370f100

Device : Nothing Phone 1
Android: Android 14
No custom rom

**Comment by KieronQuinn** [comment]
You are playing music from the device, this is normal. Now Playing does not recognise music playing from the device. 

There'd normally be a warning about this but the one about the database still downloading takes higher priority.

**Comment by mjain234** [comment]
See here, I tried using both Online and On device but on device works pretty fast and online doesn't worked for me.
https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/d1fc31a4-c450-49ac-8462-693d63e7a540
