### ISSUE TITLE
App crashes after selecting a country

### ISSUE THREAD

**Issue by TicTecOfficial** [KieronQuinn/AmbientMusicMod#246]
Running LineageOS 21 with NIkGapps, never encountered this issue on any other rom (and even older versions of lineageos)

06-08 23:56:14.602   604   604 E vold    : Failed to set project id on /data/media/0/Android/data/com.kieronquinn.app.ambientmusicmod/: Operation not supported on transport endpoint
06-08 23:56:14.626  3818  9137 E DatabaseUtils: Writing exception to parcel
06-08 23:56:14.626  3818  9137 E DatabaseUtils: java.lang.SecurityException: Unsupported path /updates/NowPlaying-v1.3.5.apk
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at com.android.providers.downloads.Helpers.checkDestinationFilePathRestrictions(Helpers.java:631)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at com.android.providers.downloads.DownloadProvider.checkFileUriDestination(DownloadProvider.java:1090)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at com.android.providers.downloads.DownloadProvider.insert(DownloadProvider.java:749)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at android.content.ContentProvider.insert(ContentProvider.java:1924)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at android.content.ContentProvider$Transport.insert(ContentProvider.java:447)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:180)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at android.os.Binder.execTransactInternal(Binder.java:1496)
06-08 23:56:14.626  3818  9137 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:1440)
06-08 23:56:14.632 12540 12540 E AndroidRuntime: FATAL EXCEPTION: main
06-08 23:56:14.632 12540 12540 E AndroidRuntime: Process: com.kieronquinn.app.ambientmusicmod, PID: 12540
06-08 23:56:14.632 12540 12540 E AndroidRuntime: java.lang.SecurityException: Unsupported path /updates/NowPlaying-v1.3.5.apk
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:3166)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:3149)
davinci:/ $
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:154)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:589)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:2209)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:2171)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at android.app.DownloadManager.enqueue(DownloadManager.java:1128)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at com.kieronquinn.app.ambientmusicmod.ui.screens.setup.installpam.SetupInstallPAMViewModelImpl.queueDownload(SetupInstallPAMViewModel.kt:171)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at com.kieronquinn.app.ambientmusicmod.ui.screens.setup.installpam.SetupInstallPAMViewModelImpl.access$queueDownload(SetupInstallPAMViewModel.kt:45)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at com.kieronquinn.app.ambientmusicmod.ui.screens.setup.installpam.SetupInstallPAMViewModelImpl$updateState$2.invokeSuspend(SetupInstallPAMViewModel.kt:78)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at com.kieronquinn.app.ambientmusicmod.ui.screens.setup.installpam.SetupInstallPAMViewModelImpl$updateState$2.invoke(Unknown Source:8)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at com.kieronquinn.app.ambientmusicmod.ui.screens.setup.installpam.SetupInstallPAMViewModelImpl$updateState$2.invoke(Unknown Source:4)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
06-08 23:56:14.632 12540 12540 E AndroidRuntime:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@985c91f, Dispatchers.Main.immediate]
06-08 23:56:15.180  9247  9247 E A       : LocalSubscriptionMixinUpdater silently ignored NullPointerException
06-08 23:56:15.180  9247  9247 E A       : java.lang.NullPointerException: Null data
06-08 23:56:15.180  9247  9247 E A       :      at com.google.apps.tiktok.g.c.aq.<init>(PG:2)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.apps.tiktok.g.c.ao.a(PG:32)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.apps.tiktok.g.c.ac.apply(PG:11)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.apps.tiktok.tracing.fi.apply(PG:13)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.common.util.concurrent.b.e(PG:3)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.common.util.concurrent.c.run(PG:130)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.apps.tiktok.concurrent.as.run(PG:71)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.apps.tiktok.tracing.fk.run(PG:24)
06-08 23:56:15.180  9247  9247 E A       :      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.common.util.concurrent.du.a(PG:3)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.common.util.concurrent.cv.run(PG:21)
06-08 23:56:15.180  9247  9247 E A       :      at com.google.common.util.concurrent.dv.run(PG:5)
06-08 23:56:15.180  9247  9247 E A       :      at android.os.Handler.handleCallback(Handler.java:959)
06-08 23:56:15.180  9247  9247 E A       :      at android.os.Handler.dispatchMessage(Handler.java:100)
06-08 23:56:15.180  9247  9247 E A       :      at android.os.Looper.loopOnce(Looper.java:232)
06-08 23:56:15.180  9247  9247 E A       :      at android.os.Looper.loop(Looper.java:317)
06-08 23:56:15.180  9247  9247 E A       :      at android.app.ActivityThread.main(ActivityThread.java:8501)
06-08 23:56:15.180  9247  9247 E A       :      at java.lang.reflect.Method.invoke(Native Method)
06-08 23:56:15.180  9247  9247 E A       :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-08 23:56:15.180  9247  9247 E A       :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by KieronQuinn** [comment]
#195
