### ISSUE TITLE
On Demand Recognition keeps failing to record audio

### ISSUE THREAD

**Issue by TicTecOfficial** [KieronQuinn/AmbientMusicMod#247]
Device: Samsung S8/dreamlte
ROM: LineageOS 20
Android Version: 13

Info: The app keeps saying that the recognition failed with the reason being that it "Failed to record audio, please try again"

I have traced the log down to this specific line(which is always the only line of log that forms when an On Demand recognition is requested: 

**06-21 06:31:08.602  4759  6875 D ConnectivityService: requestNetwork for uid/pid:10163/14139 activeRequest: null callbackRequest: 1859 [NetworkRequest [ REQUEST id=1860, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10163 RequestorUid: 10163 RequestorPkg: com.kieronquinn.app.ambientmusicmod UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647**

**Comment by TicTecOfficial** [comment]
Additional note: if the retry button is pushed continuously, sometimes the errors can vary from "A recognition is already running etc." to "Timed out waiting for response"

**Comment by KieronQuinn** [comment]
That log is nothing to do with audio recording. Can you send a full log of it happening please?

**Comment by TicTecOfficial** [comment]
> That log is nothing to do with audio recording. Can you send a full log of it happening please?

this may sound incredibly stupid, but how do you pull a log file?

**Comment by KieronQuinn** [comment]
If you're using an app, save the log using it. If you're using a command line, pipe it to a file

**Comment by TicTecOfficial** [comment]
[Uploading logcat.txt…]()

does this help?

**Comment by TicTecOfficial** [comment]
does this help 
[logcat.txt](https://github.com/user-attachments/files/15920879/logcat.txt)

**Comment by KieronQuinn** [comment]
> OnDemandManagerImpl: Sound Search failed with an error, status code 7

This error comes from the Google app, there's nothing I can do.
