### ISSUE TITLE
App cannot be installed

### ISSUE THREAD

**Issue by MartinGamesCZ** [KieronQuinn/AmbientMusicMod#248]
When i start shizuku, open the app and select the country, apk download usually fails. When it works, after download, my phone says that app cannot be installed (the app installation dialog says that)

I have Redmi Note 10 5G with Miui 14 with Shizuku running using wireless debugging

**Comment by MartinGamesCZ** [comment]
![Screenshot_2024-06-23-12-45-58-703_com.google.android.packageinstaller.jpg](https://github.com/KieronQuinn/AmbientMusicMod/assets/73077301/b0dda352-2e66-4340-a31b-7feb53e40055)

![Screenshot_2024-06-23-12-46-04-987_com.google.android.packageinstaller.jpg](https://github.com/KieronQuinn/AmbientMusicMod/assets/73077301/3661e824-e98a-4e46-bbeb-8ab98469a7e1)

**Comment by KieronQuinn** [comment]
Download the apk from https://github.com/KieronQuinn/NowPlaying/releases and install it manually, see if that works
