### ISSUE TITLE
I have one issue, all your fixes work. 

### ISSUE THREAD

**Issue by Bradford1040** [KieronQuinn/AmbientMusicMod#249]
I get the Google app on demand is not compatible, so download the APKM from apkmirror and install it, your app seems to work fine. 

The issue I have is the updated Google app breaks my Google now. What can I do to keep Google now working?

**Comment by KieronQuinn** [comment]
Probably nothing. The Google app build required for On Demand is the Pixel-only build that you're sideloading so may have incompatibilities with other devices.

There's nothing I can do about it unfortunately.

**Comment by Bradford1040** [comment]
I was just hoping you knew something, but figured that was the answer lol. Thank you for responding so quickly
