### ISSUE TITLE
Ambient Music failed to start

### ISSUE THREAD

**Issue by YkDeng200929** [KieronQuinn/AmbientMusicMod#25]
![Screenshot_20210529-084711874](https://user-images.githubusercontent.com/50475232/120052994-84a61a80-c05a-11eb-9dc0-5c41a19eee28.jpg)
System: Android 10 Pixel Expirence
Device: Xiaomi 9se (grus)

Magisk module and Exposed have installed, but I can't test recognize

**Comment by KieronQuinn** [comment]
Please post a log dump, read the FAQ.

Closing as invalid until a log is provided.
