### ISSUE TITLE
Cannot close dialog

### ISSUE THREAD

**Issue by MartinGamesCZ** [KieronQuinn/AmbientMusicMod#250]
The app is very cool, but while using it I encountered one annoying thing. I don't know if it's a problem with the app or just me.

When recognizing the song from the app directly, I didn't find a way to close the dialog with a recognized song, the only way for me is to restart the app, which is not very ux friendly.

Is there some way, or is the functionality missing?

**Comment by MartinGamesCZ** [comment]
While there is not any song, it can be closed by the back button, I don't know if it does work when there is a song (but i remember i couldn't do that about a week back).

Would be more convenient, if there was close/x button though.

![Screenshot_2024-06-29-09-17-24-825_com.kieronquinn.app.ambientmusicmod.jpg](https://github.com/KieronQuinn/AmbientMusicMod/assets/73077301/4b5e846f-43a5-4be4-9979-d2d88286ca9b)

**Comment by KieronQuinn** [comment]
I can't reproduce this. The back button works fine for me with successful local recognitions, online recognitions, failed recognitions and when the playback button is selected. Try rebooting or reinstalling.
