### ISSUE TITLE
Lockscreen Issue

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#251]
I am trying to search music through lock screen while tapping on the search icon, but I have to keep on pressing that icon to search the song. What's the issue here?

Device: Nothing Phone 1

Android version: Android 14

Device OS: Nothing OS 2.5.6

https://github.com/KieronQuinn/AmbientMusicMod/assets/70900505/ed728b64-7370-4c1c-a791-3a810f0eeb60

**Comment by KieronQuinn** [comment]
I think this should be improved in 2.4, if not fixed. If it's still not, I think you may just be seeing a delay or the "recording" status being lost between the overlay and the service, which has about a half dozen IPC calls so probably can't be fixed or improved unfortunately.
