### ISSUE TITLE
Media volume lowers down when detecting songs

### ISSUE THREAD

**Issue by devsydungo** [KieronQuinn/AmbientMusicMod#252]
v 2.3.5 (and probably older versions as well)

Whenever the app is trying to recognize a song, the currently playing media suddenly becomes quieter.

I started noticing it when i first used my wired headset (months ago), which i thought was my phone's fault, or my headset's. but today, i noticed that the music is getting quieter whenever i press recognize in the widget (although the system volume slider doesn't change).

**Comment by KieronQuinn** [comment]
Now Playing is not intended to recognise music playing on the device, this is one of the reasons why. How the system responds when a mic is in use is not in control of Ambient Music Mod, and it already will not try to recognise music when it knows music is playing, so it sounds like on your device that is not possible and there's nothing else I can do.

**Comment by devsydungo** [comment]
maybe disable recognizing when a music is playing... is that hard? i kept on turning off shizuku when i listen to my music then eneabling it again (look for a wifi first) after i listen

**Comment by KieronQuinn** [comment]
It already does disable when music is playing, that's part of the core Now Playing app, and not a feature I've added.
