### ISSUE TITLE
[Request] Widget in style of lock screen overlay

### ISSUE THREAD

**Issue by Konsl** [KieronQuinn/AmbientMusicMod#253]
Samsung recently added an option to their lock screen customization app that allows users to place arbitrary home screen widgets on their lock screen. These behave more consistently than the accessibility service overlay provided by this app. (e.g., they disappear on the pin entry screen)

If this app provided a widget in the style of what is currently included as an overlay using an accessibility service, people could use their manufacturer's implementation of lock screen widgets for a more consistent overall experience on supported devices.

**Comment by KieronQuinn** [comment]
Added in 2.4
