### ISSUE TITLE
App crashing when clicking the update button 

### ISSUE THREAD

**Issue by claymorwan** [KieronQuinn/AmbientMusicMod#256]
Every time I try to look at the update menu, it just loads forever until it crashes the app
Device : Realme 7 pro
Android version : Android 12
Device OS : Realme UI 3.0

https://github.com/user-attachments/assets/5a77d5e1-a51b-4c6c-abf4-91abda4ba100

**Comment by KieronQuinn** [comment]
Please send a log, I cannot do anything without that.

**Comment by claymorwan** [comment]
> Please send a log, I cannot do anything without that. 

Sure, how do I get the log tho, I don't know much about apps using shizuku and stuff

**Comment by KieronQuinn** [comment]
Install this: https://github.com/F0x1d/LogFox
Start it recording and make it crash, then stop recording and send the file

**Comment by claymorwan** [comment]
Here u go, there was also crash report from LogFox so imma throw them with it cuz it may be useful to u

[AmbientMusicMod.log](https://github.com/user-attachments/files/16203736/AmbientMusicMod.log)
[crash-1.log](https://github.com/user-attachments/files/16203737/crash-1.log)
[device.txt](https://github.com/user-attachments/files/16203738/device.txt)
[crash-2.log](https://github.com/user-attachments/files/16203739/crash-2.log)

**Comment by KieronQuinn** [comment]
Your device is out of memory and unable to load the database. There is nothing I can do in this case.
