### ISSUE TITLE
Issues with banking Apps

### ISSUE THREAD

**Issue by Sfinks69** [KieronQuinn/AmbientMusicMod#257]
After installing the mod, my bank's applications stopped working. They believe that the mod may somehow affect their safety and stop working..
"com.starfinanz.smob.android.sfinanzstatus" and "com.starfinanz.mobile.android.pushtan" these two applications.
Is there a way to hide them in the system since I don’t have root and use Shizuku to assign rights in the system?
I can also freeze your mod to use them and then return it back, but this is unnecessary manipulation every time and it’s not cool. I really liked your mod and I hope that you will help me find a solution

Thanks

**Comment by KieronQuinn** [comment]
#254
