### ISSUE TITLE
Lockscreen "Now Playing" Overlay Visible on Passcode Screen

### ISSUE THREAD

**Issue by Stan805** [KieronQuinn/AmbientMusicMod#258]
The lockscreen Now Playing overlay appears over the passcode screen even with Adaptive Lockscreen Overlay enabled. Is there a setting I could be missing possibly?

I tested it and it appears to be a problem on GrapheneOS, CalyxOS, and stock Pixel OS. So i assume anything AOSP based.
![Screenshot_20240729-073029](https://github.com/user-attachments/assets/e9059481-8f3c-4577-8343-7afff297aeb9)

**Comment by KieronQuinn** [comment]
#92
