### ISSUE TITLE
Trigger When Screen On Ignores Disabled Now Playing

### ISSUE THREAD

**Issue by Alexanderkocha** [KieronQuinn/AmbientMusicMod#259]
The song identification runs when Trigger When Screen On is enabled and I turn on the phone screen despite having Now Playing disabled. 

This can be replicated by:

1) Enable Trigger When Screen On
2) Disable Now Playing
3) Play song on another device nearby
4) Turn on the screen of the Ambient Music Mod device and unlock phone (not sure if unlock is necessary)
5) Wait 8 seconds and pause playback on the other device
6) Open Ambient Music Mode and enable it

You should see the song recognised despite the feature being disabled.

I hope this can be fixed as I would like to be able to have on demand offline music recognition from my notifications via the toggle, that I can disable to save battery life.

**Comment by KieronQuinn** [comment]
Fixed in 2.4
