### ISSUE TITLE
Add an animation for the now playing on the lock screen

### ISSUE THREAD

**Issue by tomasvenrura13** [KieronQuinn/AmbientMusicMod#263]
On my Samsung phone running OneUI 6.1 the "now playing" song stays in the screen for fractions of a second (noticeably) before it disappears after I swipe away from the lock screen, I don't think that's fixable but adding an animation that smooths out the disappearance or makes it disappear by going up would make it look less janky at least

**Comment by KieronQuinn** [comment]
Unfortunately this is not possible, the view is being removed rather than hidden so no animation is possible.
