### ISSUE TITLE
Crashed Frequently System Ui

### ISSUE THREAD

**Issue by caio831** [KieronQuinn/AmbientMusicMod#265]
Ok so I use Lineage Os 21 on guam (guam is the codename) and when I installed AmbientMusicMod The System Ui frequently crashed and I even had to reset my phone because it was crashing even on the LAUNCHER so can u fix this? If you need a logcat I can get one

**Comment by KieronQuinn** [comment]
Yes, please send a log

**Comment by KieronQuinn** [comment]
No log provided, closing
