### ISSUE TITLE
Server mode

### ISSUE THREAD

**Issue by PinguDEV-original** [KieronQuinn/AmbientMusicMod#267]
It would be cool to let the database stuff happen on a server and only upload the recording.

**Comment by KieronQuinn** [comment]
That's what on demand mode is. It uses a far, far bigger database and has better result detection for this reason.

**Comment by PinguDEV-original** [comment]
> That's what on demand mode is. It uses a far, far bigger database and has better result detection for this reason.

Can I selfhost that?

**Comment by KieronQuinn** [comment]
No, it's proprietary Google stuff. You can't run the recognition on anything other than Android either so would not be able to self-host the regular one either.

**Comment by PinguDEV-original** [comment]
uff yea ok makes sense
