### ISSUE TITLE
Ambient music mod crashes when selecting country

### ISSUE THREAD

**Issue by Coll147** [KieronQuinn/AmbientMusicMod#268]
When I set up Ambient Music Mod and get to select my country the app crashes.
Device: Redmi Note 9 Pro (miatoll)
Rom: CrDroid 10.8 (Android 14)
Shizuku: Sui & Magisk (27008)

https://github.com/user-attachments/assets/92e0ce2c-f88b-4ddd-a08d-d8e342609490

**Comment by KieronQuinn** [comment]
#195

**Comment by Coll147** [comment]
Sorry for not seeing it, thanks <3
