### ISSUE TITLE
Magisk google 29

### ISSUE THREAD

**Issue by binyaminyblatt** [KieronQuinn/AmbientMusicMod#269]
Would it be possible to make a magisk model that tells your phone that it has Google 29 installed with the sounds add on APK so that the Google Play store will update it that way app updates can work normally and there's no need to download from even though it's probably reputable third-party sites

**Comment by KieronQuinn** [comment]
I tried this before and no, it doesn't seem to be possible.

**Comment by binyaminyblatt** [comment]
Ok thanks for a great app
