### ISSUE TITLE
[request] option to not run at all when shizuku is not running

### ISSUE THREAD

**Issue by rexendevar** [KieronQuinn/AmbientMusicMod#271]
Every time my phone's mic gets any sound at all it sends me a notification that shizuku isn't running and it can't run AMM. I'm not on wifi right now, nor do i have a computer to start shizuku from, so i can either deal with pointless notifications all day or uninstall the app entirely. I'm getting sick of it. please release me

**Comment by KieronQuinn** [comment]
This already exists, it's called the enabled switch. Just turn it off.

**Comment by rexendevar** [comment]
where is this switch? i can't find it in the app, and i don't think i can toggle which apps can access shizuku while shizuku isn't running

**Comment by KieronQuinn** [comment]
![Screenshot_20240926-001928](https://github.com/user-attachments/assets/e07461df-1c1f-4be0-a6e7-e13ddb985d76)

**Comment by rexendevar** [comment]
![Screenshot_20240925-165404](https://github.com/user-attachments/assets/44372836-66fe-4353-8a6a-62c57b2423ee)

**Comment by KieronQuinn** [comment]
Oh well in that case I recommend just disabling the error notification channel then.

**Comment by rexendevar** [comment]
👍 done! forgot u could do that on Android if I'm honest. thank u
