### ISSUE TITLE
Ambient Music Mod crashing when entering updates menu

### ISSUE THREAD

**Issue by Areg472** [KieronQuinn/AmbientMusicMod#272]
So when I try entering the updates menu while it downloads a database, the app crashes.

**Comment by KieronQuinn** [comment]
Please provide a log

**Comment by Areg472** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a24nsxx/a24:14/UP1A.231005.007/A245FXXS6CXH1:user/release-keys'
Revision: '6'
ABI: 'arm64'
Processor: '6'
Timestamp: 2024-09-27 13:45:45.583850908+0400
Process uptime: 133s
Cmdline: com.kieronquinn.app.pixelambientmusic
pid: 25094, tid: 25233, name: superpacks-cont  >>> com.kieronquinn.app.pixelambientmusic <<<
uid: 10738
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000069
Cause: null pointer dereference
    x0  000000006fd615c0  x1  0000000000000001  x2  fffffffffffffff0  x3  00000077c31a4f00
    x4  00000077c31a4f70  x5  0000000000000004  x6  000000001414e7e8  x7  b4000077cac7f8c0
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 000000782c7f520c
    x12 00000077c31a3d80  x13 00000077c31a3da0  x14 00000077801584a1  x15 000000003fffffff
    x16 000000785e122d10  x17 000000785da186ac  x18 00000077c2df0000  x19 00000077801584a0
    x20 000000785e30c598  x21 000000785e30d000  x22 00000077c31a8000  x23 00000077c31a4f88
    x24 00000077c31a4d80  x25 0000000000100100  x26 0000000000000100  x27 000000000000004c
    x28 000000785e307d88  x29 00000077c31a5060
    lr  000000785dab5dd4  sp  00000077c31a4d40  pc  000000785dab6200  pst 0000000040001000
64 total frames
backtrace:
      #00 pc 00000000003b6200  /apex/com.android.art/lib64/libart.so (art::JniDecodeReferenceResult(_jobject*, art::Thread*)+1584) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #01 pc 00000000003b5690  /apex/com.android.art/lib64/libart.so (artQuickGenericJniEndTrampoline+368) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #02 pc 0000000000378f80  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+160) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #03 pc 00000000023af764  /memfd:jit-cache (deleted) (offset 0x2000000) (top.canyie.pine.Pine.getObject+228)
      #04 pc 0000000002205d7c  /memfd:jit-cache (deleted) (offset 0x2000000) (top.canyie.pine.entry.Arm64Entry.handleBridge+1420)
      #05 pc 0000000000362a40  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #06 pc 000000000034df38  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #07 pc 0000000000348854  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+448) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #08 pc 000000000076dfb4  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12452) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #09 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #10 pc 000000000016f4f8  [anon:dalvik-classes15.dex extracted in memory from /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk] (top.canyie.pine.entry.Arm64Entry.intBridge+0)
      #11 pc 000000000034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #12 pc 0000000000379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #13 pc 0000000000362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #14 pc 000000000035bd1c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+1928) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #15 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #16 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #17 pc 00000000008540c8  /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk (lev.b+0)
      #18 pc 000000000034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.2845697060370838518)+428) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #19 pc 000000000035c5b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4124) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #20 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #21 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #22 pc 00000000008572c4  /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk (lfe.r+0)
      #23 pc 000000000034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.2845697060370838518)+428) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #24 pc 000000000035c5b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4124) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #25 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #26 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #27 pc 000000000085643c  /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk (lfe.n+0)
      #28 pc 000000000034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.2845697060370838518)+428) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #29 pc 000000000035c5b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4124) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #30 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #31 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #32 pc 0000000000856420  /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk (lfe.m+0)
      #33 pc 000000000034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.2845697060370838518)+428) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #34 pc 000000000035c5b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4124) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #35 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #36 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #37 pc 000000000085e798  /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk (lhv.g+0)
      #38 pc 000000000034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.2845697060370838518)+428) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #39 pc 000000000035c5b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4124) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #40 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #41 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #42 pc 000000000085de6c  /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk (lhr.a+0)
      #43 pc 000000000034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.2845697060370838518)+428) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #44 pc 000000000035c5b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4124) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #45 pc 000000000076dec0  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+12208) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #46 pc 000000000037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #47 pc 000000000021067c  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~3HAyvW9VPHvz25FvJ5JSPQ==/com.kieronquinn.app.pixelambientmusic-6GaXhkPeQ1KMmXncbvKFbA==/base.apk] (oxx.e+0)
      #48 pc 000000000034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #49 pc 0000000000379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #50 pc 0000000002446a54  /memfd:jit-cache (deleted) (offset 0x2000000) (oxz.run+884)
      #51 pc 000000000222e4e4  /memfd:jit-cache (deleted) (offset 0x2000000) (java.util.concurrent.Executors$RunnableAdapter.call+132)
      #52 pc 000000000222e1e4  /memfd:jit-cache (deleted) (offset 0x2000000) (java.util.concurrent.FutureTask.run+340)
      #53 pc 000000000222de50  /memfd:jit-cache (deleted) (offset 0x2000000) (java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run+208)
      #54 pc 0000000002224b4c  /memfd:jit-cache (deleted) (offset 0x2000000) (java.util.concurrent.ThreadPoolExecutor.runWorker+444)
      #55 pc 00000000022248e0  /memfd:jit-cache (deleted) (offset 0x2000000) (java.util.concurrent.ThreadPoolExecutor$Worker.run+128)
      #56 pc 0000000002010be8  /memfd:jit-cache (deleted) (offset 0x2000000) (java.lang.Thread.run+136)
      #57 pc 0000000000362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #58 pc 000000000034def0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+132) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #59 pc 0000000000943da8  /apex/com.android.art/lib64/libart.so (_ZN3art9ArtMethod14InvokeInstanceILc86ETpTncJEEENS_6detail12ShortyTraitsIXT_EE4TypeEPNS_6ThreadENS_6ObjPtrINS_6mirror6ObjectEEEDpNS3_IXT0_EE4TypeE+60) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #60 pc 000000000063eb64  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1344) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #61 pc 000000000063e614  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8) (BuildId: 3b4ed3e67a9a04e3a37d259cd59da05b)
      #62 pc 0000000000101d0c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 59cafcd8c6514064584f920f18ea8760)
      #63 pc 0000000000095ae0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 59cafcd8c6514064584f920f18ea8760)

**Comment by KieronQuinn** [comment]
#266
