### ISSUE TITLE
Lock Screen Feature Not working

### ISSUE THREAD

**Issue by Legend-651** [KieronQuinn/AmbientMusicMod#275]
Hi, I'm using a Xiaomi Redmi Note 12 pro plus 5g buttt the now playing app doesn't work :( it is active, it runs but it doesn't detect any songs. Idk if it's a bug or if it's something wrong:(

**Comment by KieronQuinn** [comment]
If you run a manual recognition in the app, does that work? You may need to listen to the recording and adjust the settings.

**Comment by Legend-651** [comment]
I had to install the version 2.0.5 I believe? It worked on that so I updated from there, it works now thanks 🙏
