### ISSUE TITLE
database download progress bar

### ISSUE THREAD

**Issue by Watermelon1263** [KieronQuinn/AmbientMusicMod#276]
a percentage progress bar and time estimate for the database download instead of an infinite loading bar
![Screenshot_20241005_235052_Ambient Music Mod](https://github.com/user-attachments/assets/60c2b519-6c2d-4a3c-98c5-91cd414d784e)

**Comment by KieronQuinn** [comment]
This isn't possible due to the way the downloads work.

**Comment by Watermelon1263** [comment]
can I ask about the database not downloading?

I've tried force stopping a couple times reinstalling and leaving over night. it might be because I don't have wifi but it shouldn't be because I had a good data connection![Screenshot_20241006_104113_Speedtest.jpg](https://github.com/user-attachments/assets/d1531f52-398e-40dd-b0a1-b2fc8d58dfef)

I'm using shizuku without root

**Comment by Watermelon1263** [comment]
it will recognize songs but it still says it's downloading
