### ISSUE TITLE
Doesn't work on my device

### ISSUE THREAD

**Issue by IshaanPathak25** [KieronQuinn/AmbientMusicMod#279]
Ok so I'm not sure if I'm doing something wrong or something is up with my device but even after trying for numerous amounts of time, I can't get it to work on my phone. Tried clearing the data, force stopping the app and also the app has all the required permissions but for some unknown reason, it just doesn't work as intended.

**Comment by KieronQuinn** [comment]
Run a recognition and check the playback. If it sounds distorted, adjust as required until it no longer is.

If that doesn't work, it's not compatible with your device.
