### ISSUE TITLE
"Show on lock screen" not working

### ISSUE THREAD

**Issue by matto-white** [KieronQuinn/AmbientMusicMod#280]
Phone: Xiaomi 11T Pro
OS: Hyperos 1.0.4.0 Global Android 14
Root: Magisk with Sui (Zygisk) as shizuku alternative

Problem: When i try to enable the "Show on lock screen" option it sends me to the accessibility settings, i enable Ambient music mod, but when i go back to the app the setting is turned off, if i clic again it sends me againt to the settings but here is enabled.

What i tried: Update app, Update OS (From A13 to A14 and from MIUI 14 to Hyperos), clear cache, Uninstall and reinstall Ambient music mod (not Now Playing)

It used to work without problems with the same setup, I've had this problem for a few months.

**Comment by KieronQuinn** [comment]
Either the service is crashing (in which case provide a log) or it's an incompatibility with HyperOS. Please provide a log of enabling it so I can see.

**Comment by matto-white** [comment]
[Uploading log_2024_10_18_22_42_32.log…]()

Is this log ok?

**Comment by matto-white** [comment]
[Uploading log_2024_10_18_22_42_32.log…]()

Is this log ok?

**Comment by matto-white** [comment]
[log_2024_10_18_22_42_32.log](https://github.com/user-attachments/files/17441152/log_2024_10_18_22_42_32.log)

Is this log ok?

**Comment by KieronQuinn** [comment]
There's no crash in there and nothing related to the accessibility service not starting unfortunately so it's most likely an incompatibility. I don't have a device running HyperOS to debug on, so unless someone with one makes a PR to fix it, it will stay that way sadly.
