### ISSUE TITLE
"Security problem" with banking app

### ISSUE THREAD

**Issue by H4K0N42** [KieronQuinn/AmbientMusicMod#282]
After installing the app, a problem occurs with my banking app for "security reasons":
https://cloud.h4k0n.dev/s/qxs8Rg76L7MBst3/download/screen-20241031-212444.mp4

Is this a problem with this app or with my banking app?
I also use other apps that use Shizuku.

https://www.sparkasse.de/_sapp/sappmod.html:
![](https://github.com/user-attachments/assets/c73fdac2-b26e-4710-ae46-4add00504a81)

**Comment by KieronQuinn** [comment]
#254
