### ISSUE TITLE
Tidal Support

### ISSUE THREAD

**Issue by gabriel-gfs** [KieronQuinn/AmbientMusicMod#283]
It would be lovely to be able to open recognized songs in other Music apps like Tidal. Hope this doesn't require too much work.

**Comment by KieronQuinn** [comment]
I don't control the database, you'll have to ask Google for this.

**Comment by gabriel-gfs** [comment]
Would it be possible to search for the track on a different service? Maybe this is naive but when I search "tidal Name of the song" in Google it does find it. This would be enough to then click on the song.
Am I wrong in thinking this is the behavior of the Spotify integration as well. This just opens a browser with a search query in Spotify and passes a parameter causing Spotify to play the first result. Is this not possible with other services?

**Comment by KieronQuinn** [comment]
The integration with all current music services uses IDs in the database. I can't magic up IDs for tracks, so integration is not natively possible.

If you want to search for a track, I suggest you either copy the name of the track and do it that way or go via the google search option.

**Comment by gabriel-gfs** [comment]
Ok thanks 👍
