### ISSUE TITLE
Crashing Now Playing

### ISSUE THREAD

**Issue by Lobo6780** [KieronQuinn/AmbientMusicMod#285]
Hello, from the time I installed Ambient Music Mod on Motorola Edge 50 Pro I see constant crashes using LogFox. Can you check what is the reason for this? All zipped.
[crash-com-kieronquinn-app-pixelambientmusic-06_11-22-33-56_680.zip](https://github.com/user-attachments/files/17654425/crash-com-kieronquinn-app-pixelambientmusic-06_11-22-33-56_680.zip)
[crash-com-kieronquinn-app-pixelambientmusic-06_11-23-03-09_005.zip](https://github.com/user-attachments/files/17654426/crash-com-kieronquinn-app-pixelambientmusic-06_11-23-03-09_005.zip)
[crash-com-kieronquinn-app-pixelambientmusic-06_11-23-31-12_185.zip](https://github.com/user-attachments/files/17654427/crash-com-kieronquinn-app-pixelambientmusic-06_11-23-31-12_185.zip)

**Comment by KieronQuinn** [comment]
#266
