### ISSUE TITLE
Ambient Music Mod on wearos?

### ISSUE THREAD

**Issue by Coll147** [KieronQuinn/AmbientMusicMod#286]
I don't think there is support for wearos, but to test, I have installed Shizuku on WearOs2 (ticwatch pro 3) (android9) and installed ambient Music Mod, but when I open ambient Music Mod it instantly closes. 
Is there anything that can be done? Anyway, if there is any log I can provide, let me know.

**Comment by KieronQuinn** [comment]
It's not possible to run it on the watch. There's already an issue open for a companion app.

#46
