### ISSUE TITLE
Provide YouTube link

### ISSUE THREAD

**Issue by ThreeDeeJay** [KieronQuinn/AmbientMusicMod#287]
I'm assuming once a song is recognized, the app knows the YouTube video ID to be able to get the thumbnail, but I don't see it anywhere. It would be nice to have it so we can play the song on YouTube, or share it with an app like [Redomi](https://github.com/acszo/Redomi) (or maybe even [implement it directly into the app like this](https://github.com/kawaiiDango/pano-scrobbler/issues/484#issuecomment-2390845339)) to get links to other streaming platforms so we can add recognized songs to our libraries. 👀👌 

And by the way, do the offline databases also contain the YouTube ID or does the app just perform a quick search using the detected artist and title? 🤔

**Comment by KieronQuinn** [comment]
It already does.

![Screenshot_20241206-211250](https://github.com/user-attachments/assets/80ce6f43-5310-4dd5-874a-8285a730765a)#

The YouTube link _is_ the source of the album art.

**Comment by ThreeDeeJay** [comment]
Huh, I don't get that extra bar at the bottom for some reason 🤔 
Is it part of the new database? It's stuck updating and I can't quite figure out why, but apparently the apps are up to date.
![image](https://github.com/user-attachments/assets/7492d612-845a-4280-94ae-c93787ac064b)
