### ISSUE TITLE
Nearby music not recognized. 

### ISSUE THREAD

**Issue by TMReaper** [KieronQuinn/AmbientMusicMod#288]
Only way it recognizes music is thru the recognition button in the app. It does not recognize music in the background. For example, if there is music playing from a different device and my phone is laying right next to the device, it does not recognize the music and display it on the lock screen. I would have to open the app and then click the recognize button for it to work; it does not do it automatically. I am running Android 14, S23U thru shizuku, my phone is not rooted. Thanks for your help!

**Comment by TMReaper** [comment]
I tried playing around with the settings as well, but nothing seems to make it work in the background. Right now, I have alternative encoding on, and gain set to 0.3, but I tried all levels of the gain, but did not make a difference. Additionally, it says now playing app running in the background on my notifications page, but just does not recognize any songs.

**Comment by KieronQuinn** [comment]
If it works manually but not in the background, it's being killed by the system and is not something I can fix. Follow the appropriate steps here: https://dontkillmyapp.com/
