### ISSUE TITLE
Fails to start on Android 12

### ISSUE THREAD

**Issue by shivam0664** [KieronQuinn/AmbientMusicMod#32]
[ambient_music_mod_log_dump_2021-11-05T10_38_55.486.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/7480757/ambient_music_mod_log_dump_2021-11-05T10_38_55.486.zip)
It never starts. I have done everything right but still!

**Comment by KieronQuinn** [comment]
There's no error in those logs, in fact it looks like it begins to start without issue. What device is this on? Maybe try rebooting?

**Comment by shivam0664** [comment]
Device is sweetin i.e Redmi Note 10 Pro . I tried everything but it never starts and also headphone jack get destroyed and also WhatsApp calls audio sounds robotic . It's on Android 12. Audio stuters sometimes. Maybe rn it's not android 12.

**Comment by shivam0664** [comment]
Also I followed this video to install 
https://youtu.be/XtUQ2ukMNG8

**Comment by KieronQuinn** [comment]
As it's also broken your audio, I'm going to say that it's probably not compatible with your device and there's nothing I can do about that, sorry.
