### ISSUE TITLE
Redmi K20 Pro; Ambient music failed to start

### ISSUE THREAD

**Issue by RadTDM** [KieronQuinn/AmbientMusicMod#37]
Device Raphael
PEX android 12
Magisk 24.1 
Lsposed zygisk

Greetings, I have encountered a problem when trying to get the module to work. Below, I have attached the log dump. Thank you

[ambient_music_mod_log_dump_2022-03-06T22_36_24.96.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/8192832/ambient_music_mod_log_dump_2022-03-06T22_36_24.96.zip)

**Comment by KieronQuinn** [comment]
The module is currently broken on most Android 12 devices. I am waiting for OnePlus to update my test device (a 7TP) to 12 to fix it.

**Comment by RadTDM** [comment]
okay, thanks for the info
