### ISSUE TITLE
Says Exposed is not installed but is installed 

### ISSUE THREAD

**Issue by KillerKaninchen1284** [KieronQuinn/AmbientMusicMod#39]
I'm on the OP 6, with awaken os aka. Pixel experience Rom android 12.
I have installed everything like the guide say's, but if I test the mod is says failed to start. And in the log dump it says Xposed not installed.
![Screenshot_20220422-125754_Shell.png](https://user-images.githubusercontent.com/83061008/164703567-5fee98d9-0268-4b97-88c3-76ca173fb619.png)
And![Screenshot_20220422-125749_Shell.png](https://user-images.githubusercontent.com/83061008/164703610-b77ef947-29f7-481c-a5ae-9492a077cbe5.png)

I have Lsposed

**Comment by KillerKaninchen1284** [comment]
![Screenshot_20220422-131355_HTML-Anzeige.png](https://user-images.githubusercontent.com/83061008/164703957-d67b8007-7799-4e1c-9eb8-f98cfb3d0ee2.png)

**Comment by KieronQuinn** [comment]
#38
