### ISSUE TITLE
Ambient Music Module Incompatible 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#40]
Hi there
In my device, Ambient music is saying "Module Incompatible" but can I still use this and can you explain me about this error
![Screenshot_20220427-034200_Ambient Music Mod](https://user-images.githubusercontent.com/70900505/165401191-1f4f0ed0-02cf-4a8f-99fe-feaac3ce3955.png)

**Comment by KieronQuinn** [comment]
What Android version?

**Comment by mjain234** [comment]
Android version 12

**Comment by KieronQuinn** [comment]
#38
