### ISSUE TITLE
Audio playback distored.

### ISSUE THREAD

**Issue by MSD-3** [KieronQuinn/AmbientMusicMod#42]
Great job on releasing V2 .
But there is a lack of option to reduce amplification, my playback is getting distorted at even at 1xGrain.

**Comment by KieronQuinn** [comment]
With no gain (1x), there's no amplification applied at all. Make sure you've not got any conflicting audio mods installed (especially old Ambient Music Mod), and reboot

**Comment by tejas2004** [comment]
Same issue here

**Comment by KieronQuinn** [comment]
Managed to reproduce on an old device.

Added an option in 2.0.1 to reduce the gain below 1.0x (where it did nothing). Nothing more than this can be done, since the audio that's being used is raw from the mic - there's no input volume control as far as I know.
