### ISSUE TITLE
Mod app loads forever

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/AmbientMusicMod#44]
So I noticed this behavior where the app needs to have it's cache cleared and force stopped or else the "now playing" tab would load continuously/way longer than usual

https://user-images.githubusercontent.com/40364718/174500410-ff88d675-ade0-4111-b3e3-4d49d429582e.mp4

**Comment by KieronQuinn** [comment]
If you see this, force stop and restart the app. Cache clearing isn't necessary, it's just the connection between AMM <> Now Playing getting stuck. I've tried, can't fix it, seems to get stuck somewhere in the system.
