### ISSUE TITLE
[Request] Tasker Enable/Disable intents

### ISSUE THREAD

**Issue by rodrigoswz** [KieronQuinn/AmbientMusicMod#45]
It would be great to have some intents automate as we want in Tasker. Some like:

- Enable Now Playing
- Disable Now Playing
- Start Recognise On Device
- Start Recognise Online

**Comment by KieronQuinn** [comment]
Ah, I knew this would come up. Unfortunately, this would leave the system open to abuse. 

There's no way to know where a broadcast has come from, so I can't make it only work from Tasker. Open it to Tasker, open it to any app that wants to spam recognitions and abuse the system, draining battery and - most importantly - keeping the microphone active.

For now, it's a no. You *can* make it fire the recognition dialog that shows with the app shortcut though, `.ui.activities.RecognitionModalActivity` is exported.

**Comment by rodrigoswz** [comment]
Re-opening this issue partially, is there any broadcast receiver just to toggle AMM service?
Just to create something like how "Disable at Bedtime" works, but under the conditions I want.

**Comment by KieronQuinn** [comment]
Added in 2.3, I also was able to implement a token-based access restriction system which made it safe for intents to run recognitions too, so your original request has been fully added.

Check out the [Wiki page](https://github.com/KieronQuinn/AmbientMusicMod/wiki/External-Access) for examples of using it with Tasker

**Comment by rodrigoswz** [comment]
Kieron, this is absolutely unexpected, thank you so MUCH for reconsidering! I imagine so many uses with this...

I just tested all intents and works perfectly. Amazing work like always, thank you again 🙏🏻
