### ISSUE TITLE
AmbientMusic Recognise Feature 

### ISSUE THREAD

**Issue by Craftyboss2** [KieronQuinn/AmbientMusicMod#48]
On Samsung devices without root, the Recognise feature only records static. However, when recording via another app to recognize music (ie. Shazam, Google app, or Google assistant), the song gets recognized mostly without any issue.

Adjusting Gain does not yield any improvement, with static still largely remaining.

Using AmbientMusicMod 2.0.1 apk via Shizuku.

**Comment by MSD-3** [comment]
Same problem here , using with root on Realme XW

Don't have any conflicting apps installed

**Comment by KieronQuinn** [comment]
#47
