### ISSUE TITLE
Ambient Mod not showing on Lockscreen

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#49]
Hi there
I just recently updated your Ambient music mod and found some of the features is not working for me. 
1. Now playing is not showing up on Lockscreen
2. Offline recognition not working

Android version - Android 12
Device - Realme 2 Pro
ROM - Derpfest 
Magisk - magisk v23.0

**Comment by mjain234** [comment]
Is it connected to lockscreen ambient music not showing or it affects offline recognition feature?

**Comment by KieronQuinn** [comment]
Adaptive Lock Screen Overlay does not work on all devices, and can cause it to not display at all (that's why it has a warning). If you have it enabled, disable it and it will probably start working

Now, if you don't have the on demand option in the Lock Screen settings enabled (which requires On Demand to be enabled obviously), the overlay will not show anything unless a song is recognised. This is normal, as it has nothing to display.

**Comment by mjain234** [comment]
Ok, I have On demand Recognition available and it shows after it recognises the song but it works with online recognition, what about offline recognition? When I click or try to recognise through offline one, it doesn't recognise anything

**Comment by KieronQuinn** [comment]
You probably have the same crackling issue as others, a release adding an option that works around this is imminent. If the overlay is working, I'll close this issue.

**Comment by pranavphadke** [comment]
In my case, the overlay stopped working without changing anything in the app. It worked initially but after a restart, it stopped. I do get notifications and it recognizes the song but no overlay on lockscreen. Running non-rooted Samsung S21 Ultra on Android 12. Started Shizuku via adb connected to a computer as well as using wireless debugging. Disabled all battery optimization. Adaptive lockscreen is disabled as well.

**Comment by pranavphadke** [comment]
> In my case, the overlay stopped working without changing anything in the app. It worked initially but after a restart, it stopped. I do get notifications and it recognizes the song but no overlay on lockscreen. Running non-rooted Samsung S21 Ultra on Android 12. Started Shizuku via adb connected to a computer as well as using wireless debugging. Disabled all battery optimization. Adaptive lockscreen is disabled as well.


After the update it is working

**Comment by KieronQuinn** [comment]
If you are using Smart Lock, you had #76

**Comment by pranavphadke** [comment]
> If you are using Smart Lock, you had #76

Awesome. Thanks
