### ISSUE TITLE
Sound Model incompatible on Pixel

### ISSUE THREAD

**Issue by Draic** [KieronQuinn/AmbientMusicMod#5]
I want to use this implementation on my pixel 4 because I gave up using the original feature after Google forced analytics for pixel 4 and above. 

Sad to see the device is not recognized as being compatible :(
if this is a reimplantation, why is it not compatible with the original devices?

**Comment by KieronQuinn** [comment]
Most Pixels will kind of _half_ work, but you'll need to provide the correct sound model for the device from the stock ROM and not modify sound_trigger_platform_info. 

Unfortunately for you, the Pixel 4 doesn't fit this either as it's a special case. The P4 actually has a custom chip in it for sound recognition, and uses a totally different Ambient implementation, so this module will quite likely never work on it.

**Comment by Extarys** [comment]
@KieronQuinn On a similar note, I imagine this won't work on Pixel 6? I wish I could use this nice feature without the G00gle crap :/

This is a very nice project nonetheless, thank you!
