### ISSUE TITLE
Error due to connection timeout to service popping up minute for minute whenever playing back audio in-app

### ISSUE THREAD

**Issue by AgentHV** [KieronQuinn/AmbientMusicMod#50]
First, congrats for releasing v2/v2.1, you've really outdone yourself. Thanks to the update the app is finally working well on my OnePlus 8 Pro AOSP 12.1.

However I still have a minor issue: Whenever I play audio in an app like TikTok, YouTube or Plex I get the error notification in set intervals while playing back (a video for example). Would it be possible to check for other apps playing audio and if they do not try to run the recognition?

**Comment by KieronQuinn** [comment]
Yes, it does that already. If the notification is showing regardless that's a bug.

**Comment by KieronQuinn** [comment]
The notification has been removed in 2.0.2 as it was pretty useless anyway. Thanks for the report!
