### ISSUE TITLE
Overlay issue

### ISSUE THREAD

**Issue by duramato** [KieronQuinn/AmbientMusicMod#51]
- Oneplus 8
- Android 12
- Version 2.0.1

When installing the overlay a round hole near the supposed camera location appears and the clock disappears from the statusbar. The power button seems to be remapped from opening the power menu, to opening the Google Assistant. To open the power menu I need to do Power+Vol Up.

See attached image:
![image](https://user-images.githubusercontent.com/10121067/174564906-f5497b42-22a6-47a2-920d-d4c0c15179db.png)

Any other info needed let me know.

**Comment by KieronQuinn** [comment]
Not related to the on demand overlay, it must be interacting with the system in some way. It only changes one string so there's nothing I can do, sorry.

**Comment by duramato** [comment]
How can I enable it without using Magisk?  Want to see if it's an issue with magisk

**Comment by KieronQuinn** [comment]
You can't, it requires Magisk.

**Comment by duramato** [comment]
Thank you for the reply, but that module's page says it is deprecated and it does not work. 
So it seems a fix within Ambient Music Mod's module may be needed?

I tried installing it:

```
- Copying zip to temp directory
- Installing Overlay_Mount_Fix-v2_4-9.zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/up.julzm.c/cache/flash/install.zip
  inflating: module.prop
*******************
 Overlay Mount Fix 
*******************
*******************
Archive:  /data/user/0/up.julzm.c/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/up.julzm.c/cache/flash/install.zip
  inflating: customize.sh
  inflating: post-fs-data.sh
  inflating: README.md
  inflating: service.sh
  inflating: module.prop
 Powered by Magisk 
*******************
- Extracting module files
No overlay mounts detected!
No need for this mod! Aborting!
! Installation failed
```

**Comment by KieronQuinn** [comment]
I've attached a new module that uses the QuickSwitch overlay code if someone could try it please

[OnDemandOverlay.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/8994289/OnDemandOverlay.zip)

**Comment by UltraHQ** [comment]
> The above overlay is included in the 2.0.3 release, but can be removed if it breaks more. Awaiting further feedback.

Magisk module in the release gives "Installation Failed!"
(The one attached here works though)

The magisk module is still bootlooping on the Samsung Galaxy A72.

**Comment by PalmDevs** [comment]
Same as above. In the release page, it fails. This one works perfectly fine. I'm not a Sansung user, so no bootloop.

**Comment by KieronQuinn** [comment]
> > The above overlay is included in the 2.0.3 release, but can be removed if it breaks more. Awaiting further feedback.
> 
> Magisk module in the release gives "Installation Failed!" (The one attached here works though)
> 
> The magisk module is still bootlooping on the Samsung Galaxy A72.

Could you please zip up the /data/adb/modules/OnDemandOverlay folder, and send it here, thanks.

**Comment by KieronQuinn** [comment]
In the meantime I've swapped the one on the releases page with the working one.

**Comment by UltraHQ** [comment]
> > > The above overlay is included in the 2.0.3 release, but can be removed if it breaks more. Awaiting further feedback.
> > 
> > 
> > Magisk module in the release gives "Installation Failed!" (The one attached here works though)
> > The magisk module is still bootlooping on the Samsung Galaxy A72.
> 
> Could you please zip up the /data/adb/modules/OnDemandOverlay folder, and send it here, thanks.

[OnDemandOverlay (1).zip](https://github.com/KieronQuinn/AmbientMusicMod/files/8996465/OnDemandOverlay.1.zip)

**Comment by KieronQuinn** [comment]
> > > > The above overlay is included in the 2.0.3 release, but can be removed if it breaks more. Awaiting further feedback.
> > > 
> > > 
> > > Magisk module in the release gives "Installation Failed!" (The one attached here works though)
> > > The magisk module is still bootlooping on the Samsung Galaxy A72.
> > 
> > 
> > Could you please zip up the /data/adb/modules/OnDemandOverlay folder, and send it here, thanks.
> 
> [OnDemandOverlay (1).zip](https://github.com/KieronQuinn/AmbientMusicMod/files/8996465/OnDemandOverlay.1.zip)

And when you install it (just install it again and then immediately disable it after), what directory does it say it's installing the overlay to?

**Comment by UltraHQ** [comment]
> > > > > The above overlay is included in the 2.0.3 release, but can be removed if it breaks more. Awaiting further feedback.
> > > > 
> > > > 
> > > > Magisk module in the release gives "Installation Failed!" (The one attached here works though)
> > > > The magisk module is still bootlooping on the Samsung Galaxy A72.
> > > 
> > > 
> > > Could you please zip up the /data/adb/modules/OnDemandOverlay folder, and send it here, thanks.
> > 
> > 
> > [OnDemandOverlay (1).zip](https://github.com/KieronQuinn/AmbientMusicMod/files/8996465/OnDemandOverlay.1.zip)
> 
> And when you install it (just install it again and then immediately disable it after), what directory does it say it's installing the overlay to?

[magisk_install_log_2022-06-28T02.26.57.log](https://github.com/KieronQuinn/AmbientMusicMod/files/8996576/magisk_install_log_2022-06-28T02.26.57.log)

**Comment by duramato** [comment]
I've tested this new version, but it still has the same issue I had in the original post, the one from the screenshot.

**Comment by KieronQuinn** [comment]
[OnDemandOverlay.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9001129/OnDemandOverlay.zip)

Try this one maybe?

**Comment by UltraHQ** [comment]
> [OnDemandOverlay.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9001129/OnDemandOverlay.zip)
> 
> Try this one maybe?

Hi, is it for me or @duramato?

**Comment by KieronQuinn** [comment]
Both.

**Comment by UltraHQ** [comment]
> So yours is now installing to the correct location (vendor not product). I wonder if the empty folder is causing problems, try this
> 
> [OnDemandOverlay.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9001467/OnDemandOverlay.zip)

It's also causing an bootloop. Maybe it's the APK, that's causing the issues?

**Comment by KieronQuinn** [comment]
> > So yours is now installing to the correct location (vendor not product). I wonder if the empty folder is causing problems, try this
> > [OnDemandOverlay.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9001467/OnDemandOverlay.zip)
> 
> It's also causing an bootloop. Maybe it's the APK, that's causing the issues?

Shouldn't be, it's only changing one singular string value. You could try capturing a log maybe, that might help but I doubt it.

**Comment by UltraHQ** [comment]
> > > So yours is now installing to the correct location (vendor not product). I wonder if the empty folder is causing problems, try this
> > > [OnDemandOverlay.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9001467/OnDemandOverlay.zip)
> > 
> > 
> > It's also causing an bootloop. Maybe it's the APK, that's causing the issues?
> 
> Shouldn't be, it's only changing one singular string value. You could try capturing a log maybe, that might help but I doubt it.

I'm not sure how. I always boot into safe mode to remove the module.
Just out of interest, installing the app to priv-app won't work, right?

**Comment by duramato** [comment]
Now it's working for me. The latest zip you've sent.

**Comment by KieronQuinn** [comment]
Ok, after a lot of work I was able to get the On Demand service to run as root, so bypassing the need for an overlay. Unfortunately this has a downside, which is that the only way it would record audio was through the HOTWORD mic, the same source as regular on-device recognition. This means it _may_ be susceptible to the same crackling issue as that, but this time I wouldn't be able to fix it. 

I've attached a test APK. If you could test it on a Samsung device, that would be great. Even better if that device had the crackling issue (and I think they all did) - does On Demand work?

You will need to have started Shizuku as root, or use Sui for this to work.

APK zipped up so GitHub will let me attach it:

[app-release.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9006593/app-release.zip)

**Comment by UltraHQ** [comment]
> Ok, after a lot of work I was able to get the On Demand service to run as root, so bypassing the need for an overlay. Unfortunately this has a downside, which is that the only way it would record audio was through the HOTWORD mic, the same source as regular on-device recognition. This means it _may_ be susceptible to the same crackling issue as that, but this time I wouldn't be able to fix it.
> 
> I've attached a test APK. If you could test it on a Samsung device, that would be great. Even better if that device had the crackling issue (and I think they all did) - does On Demand work?
> 
> You will need to have started Shizuku as root, or use Sui for this to work.
> 
> APK zipped up so GitHub will let me attach it:
> 
> [app-release.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/9006593/app-release.zip)

Hi, good news!
It works.

I'm able to use On Demand with this APK, it recognizes songs.

**Comment by UltraHQ** [comment]
> Great! I'll include that as a second option for people who can't use the overlay then.

Awesome! Do you still need the logcat?

**Comment by KieronQuinn** [comment]
> > Great! I'll include that as a second option for people who can't use the overlay then.
> 
> Awesome! Do you still need the logcat?

If you can, would be great to know what's causing the overlay to fail too

**Comment by duramato** [comment]
Great job! Thank you.
Have you thought of adding the new update URL magisk feature to the magisk module? 
I'm referring to this: [`[App] Allow modules to specify an update URL for in-app update + install`](https://topjohnwu.github.io/Magisk/changes.html#v240:~:text=%5BApp%5D%20Allow%20modules%20to%20specify%20an%20update%20URL%20for%20in%2Dapp%20update%20%2B%20install)

**Comment by KieronQuinn** [comment]
I'm aware of that but since the module isn't intended to be updated I don't think it's worth it. If it works now, there's no reason for you to update it in the future since no new functionality will ever be added.
