### ISSUE TITLE
Sound seems too loud

### ISSUE THREAD

**Issue by DylanAkp** [KieronQuinn/AmbientMusicMod#52]
I've made a first test on a OnePlus 8 Pro (Pixel Experience) and it works perfectly.
I've made the same test without root on Galaxy S22+ running OneUI
According to the playback function, the music is not audible at all, I can only hear distortions and strange noises, even with gain at 0.1x.
Every microphone is clear and working (tested using camera, call, recorder)

**Comment by KieronQuinn** [comment]
#47
