### ISSUE TITLE
Ask Google after song recognition not working

### ISSUE THREAD

**Issue by tejas2004** [KieronQuinn/AmbientMusicMod#53]
When the song is recognised, I select "Ask Google" nothing happens. Is this not working (known bug)?
Anyways now playing working very good on my device, very much thanks for such a mod.
![Screenshot_20220620-201842_Ambient Music Mod](https://user-images.githubusercontent.com/42291092/174628747-cbeb577a-65a4-40bb-ab67-1b203d54867e.png)

**Comment by KieronQuinn** [comment]
Do you have the Google app installed? It opens Assistant.

**Comment by tejas2004** [comment]
> Do you have the Google app installed? It opens Assistant.

Ofcourse

**Comment by tejas2004** [comment]
Caught the bug on recording
https://photos.app.goo.gl/WGyzyEBQzeRzYc5PA

**Comment by KieronQuinn** [comment]
Please send a log including the time when you try to press the button

**Comment by tejas2004** [comment]
> Please send a log including the time when you try to press the button

Sorry, idk how to include time of pressing button, but I have collected the log exactly when I pressed the button. Hope it helps you.
[Log_2022-06-20_22-07-27.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/8942356/Log_2022-06-20_22-07-27.txt)

**Comment by KieronQuinn** [comment]
That looks good, but it's not showing any error. Either it's not something that can be fixed, or the log needs to run on for a little longer after the button was pressed to catch up

**Comment by tejas2004** [comment]
> That looks good, but it's not showing any error. Either it's not something that can be fixed, or the log needs to run on for a little longer after the button was pressed to catch up

Now?
[Log_2022-06-20_22-17-06.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/8942400/Log_2022-06-20_22-17-06.txt)

**Comment by KieronQuinn** [comment]
Still not seeing anything. What are you using to make a log?

**Comment by tejas2004** [comment]
> Still not seeing anything. What are you using to make a log?

Logcat extreme app

**Comment by KieronQuinn** [comment]
Shouldn't do, but I've managed to reproduce it anyway so I don't need a log anymore. Thanks for your help

**Comment by tejas2004** [comment]
> Shouldn't do, but I've managed to reproduce it anyway so I don't need a log anymore. Thanks for your help

Nice, hope this issue gets resolved soon.
