### ISSUE TITLE
Servers offline?

### ISSUE THREAD

**Issue by Quinten0508** [KieronQuinn/AmbientMusicMod#56]
Had issues where databases wouldn't download and the app could not connect to the server so I tried a reinstall. Now it's not even able to fetch the `Now Playing` apk file. Are the servers down for maintenance?
![Screenshot_20220620-221100_Ambient Music Mod.png](https://user-images.githubusercontent.com/55107945/174671830-e404e576-2308-413c-9cda-23decf1d906f.png)

**Comment by KieronQuinn** [comment]
It pulls from GitHub, so no they're not offline since you commented here. Reboot and try again.
