### ISSUE TITLE
Music Database won't download

### ISSUE THREAD

**Issue by Andrew-M3373** [KieronQuinn/AmbientMusicMod#57]
The Music Database will not finish downloading and it just sits on the loading screen. I even left it overnight but still didn't finish. I've tried rebooting, reinstalling and changing the settings. I also gave it a couple hours to download each time, but it still never finishes. Is this expected, or do you have any other ideas?
![Screenshot_20220620-151218_Trebuchet](https://user-images.githubusercontent.com/55599662/174678460-c09d8454-ac76-4edd-8785-a7851e492a01.png)

**Comment by KieronQuinn** [comment]
There's nothing I can do about this unfortunately, that progress bar means it's registered as downloading, and the downloading part of Now Playing is beyond the mod. All I can suggest is check your settings again, make sure you're connected to WiFi that isn't blocking or metered and reboot.

**Comment by Andrew-M3373** [comment]
Thank you, I will try that. How long should it normally take to download?

**Comment by KieronQuinn** [comment]
On a fast connection, couple of minutes. It's about 250-300MB, so just estimate that for your connection

**Comment by Andrew-M3373** [comment]
Alright, it still won't work... Is there a way to download the file directly?

**Comment by Mahas1** [comment]
A workaround I have observed is:
step 1 - start the download/update of the database
step 2 - wait for a decent amount of time, when you're sure it has finished downloading
step 3 - Settings > Apps > Ambient Music Mod > Clear data
step 4 - set things up again, but don't touch the database
step 5 - it works(?)

Images
![Screenshot_20230318-173919_Ambient Music Mod](https://user-images.githubusercontent.com/82939599/226105374-6ab26ba4-e1d3-4744-91a9-ca98c605f947.png)
![Screenshot_20230318-174211_Ambient Music Mod](https://user-images.githubusercontent.com/82939599/226105375-b3f29e6b-3ff0-48ae-860c-3fc64ba3dcd7.png)

**Comment by KieronQuinn** [comment]
Yeah, no. You've just confused the UI. 

The only method that works 100% is to let it sit and it will download eventually. Being impatient can in face break it entirely.
