### ISSUE TITLE
Cant detect music initially, but does later

### ISSUE THREAD

**Issue by shailantani** [KieronQuinn/AmbientMusicMod#58]
Hey so this is an interesting issue, so I was playing a song and clicked on recognise and it wouldnt. But once i stopped playing, and then clicked recognise and then started playing while the recognition was going on, it detected it perfectly. Because of this. I cant use the widget either.
(Btw, had to enable "use alternative encoding" to fix the distortion

https://user-images.githubusercontent.com/98448265/174683392-42473efb-fd77-4502-9ea4-a79f795df3aa.mp4

)

**Comment by KieronQuinn** [comment]
This is normal, recognitions don't work for music that is playing locally. You managed to break the check by starting the track mid-recognition.

Now Playing is for **ambient music**, not music playing from the device itself.

**Comment by shailantani** [comment]
> 

Oh perfect perfect makes sense, thank you so much.
cheers and thanks for this great app!
