### ISSUE TITLE
Privacy statement

### ISSUE THREAD

**Issue by Donkey-Doug** [KieronQuinn/AmbientMusicMod#59]
I believe all analysis is done on device and there are no privacy concerns. It would be nice if there was a brief explanation or privacy statement in the readme.

**Comment by KieronQuinn** [comment]
There's a whole section on privacy in the Medium article, but yeah I'll add it to the readme

https://medium.com/@KieronQuinn/now-playing-ambient-music-mod-v2-93cd4042cc11#:~:text=Protecting%20Your%20Privacy
