### ISSUE TITLE
Test recognition failed

### ISSUE THREAD

**Issue by sanjeevstunner** [KieronQuinn/AmbientMusicMod#6]
![Screenshot_20210420-141540](https://user-images.githubusercontent.com/42514333/115369480-c46d1d00-a1e5-11eb-92e3-28fa0a2a7fb3.png)

Tried all the stuff mentioned in the trouble shooting guide.

 Handset redmi note 6 pro-tulip

Rom Posp April, gapps nik gapps full latest

Magisk latest, edxposed and riru installed

Whitelisted the apps as said in troubleshooting guide and also disabled battery optimization for those apps

**Comment by KieronQuinn** [comment]
Please provide a log dump (read the FAQ), this is not a valid issue without one.

I will reopen if you provide one.

**Comment by janshatad** [comment]
![Screenshot_20210420-172246_Ambient_Music_Mod](https://user-images.githubusercontent.com/35929904/115372566-a1e6fe00-a1fd-11eb-869a-5dc5c3f3264f.png)
I did all the instructions and did fail, 
Using AOSP ROM Evolution X Official
Device: Redmi Note 6 Pro
Using Magisk 21.1 with a module riru edExposed and but fail. , Then also the LsPosed and still the same Ambient Music Mod when testing is failed result Ambient Music Failed to Start.

**Comment by sanjeevstunner** [comment]
Whats invalid about that

I request an explanation

**Comment by KieronQuinn** [comment]
The explanation is in the reply before the issue was closed. Provide a log.

**Comment by sanjeevstunner** [comment]
Sorry man, didn't notice. Here is the logs btw 
[Uploading 2021-04-20-16-30-07.txt…]()

**Comment by sanjeevstunner** [comment]
[2021-04-20-16-30-07.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/6342954/2021-04-20-16-30-07.txt)

**Comment by KieronQuinn** [comment]
That is not a log dump, please read the FAQ.
