### ISSUE TITLE
[Request] Dark text stroke

### ISSUE THREAD

**Issue by ralph950412** [KieronQuinn/AmbientMusicMod#60]
Adding dark border around the text could make it more visible, just like how the Owner Info displayed. 
![Screenshot_20220621-112536_Pixel Launcher](https://user-images.githubusercontent.com/88758544/174710010-448584c4-1a7c-435c-897c-207ee9eac6f8.png)

**Comment by KieronQuinn** [comment]
Added both in 2.0.3
