### ISSUE TITLE
Microphone Input when i click playback is buzzy even though its not

### ISSUE THREAD

**Issue by emiljano539** [KieronQuinn/AmbientMusicMod#63]
Music recognition doesn't work for me 
device : Oneplus 6 , 
Running Android 11 , 
DotOS Custom ROM .
Microphone Input when I click playback is sounds buzzy even though its not in real life . It seems something is broken when the application is trying to detect the microphone.
Already tried messing up with the gain slider but It doesn't seem to do anything...
If there's any log I can provide , reply me

**Comment by KieronQuinn** [comment]
Enable the Alternative Encoding option, it was added to fix this.
