### ISSUE TITLE
Now Playing shows creepy songs when actually I was sleeping 

### ISSUE THREAD

**Issue by morta5** [KieronQuinn/AmbientMusicMod#64]
Hi,
I know this is kinda weird but I used this app for 3 days now and just two minutes ago it showed me a song while I actually didn't listen to anything.
And there is also a song in the history from yesterday at a time I was sleeping and didn't listen to any music. The song is also kinda creepy.
Screenshots of the history attached 
![Screenshot_20220622-165456~2](https://user-images.githubusercontent.com/66527936/175063521-f71bc272-1380-440e-942d-1b9c4495a3f2.png)
![Screenshot_20220622-165514-273](https://user-images.githubusercontent.com/66527936/175063550-67a9d19b-18ff-466e-bbc7-d1fb41c1da3d.png)

**Comment by KieronQuinn** [comment]
The model is detecting those songs, nothing to do with Ambient Music Mod. It's accurate, but not perfect.

**Comment by morta5** [comment]
But is it normal that it detects a song when actually there's just silence?
The first screenshot was from 04 am. There was definitely no song playing at that time and the room the phone was in was completely silent

**Comment by KieronQuinn** [comment]
There was probably noise detected by the mic. It's very sensitive.

**Comment by morta5** [comment]
Okay. Thanks for your help and making this mod!
