### ISSUE TITLE
Crash on Android 10 (ContentProvider)

### ISSUE THREAD

**Issue by Darkmagister** [KieronQuinn/AmbientMusicMod#66]
hello, i've installed the app after installing now playing it keep saying that now playing it crashed, and after few minutes try again few time, keep saying app crashed unfortunately the message disappear immediately and i don't know what to do
ambient music mod  2.0.2
now playing 1.0.1

android 10
miui 12.1
mi mix 2s

**Comment by KieronQuinn** [comment]
Please provide a log, I can't do anything without that

**Comment by Darkmagister** [comment]
i don't really know how to do it, because when the popup of crashed app appear it will disappear immediately and i can not click on show details

**Comment by KieronQuinn** [comment]
https://www.xda-developers.com/how-to-take-logs-android/

I need a system log

**Comment by KieronQuinn** [comment]
Thanks, looks like an oversight on my part with old APIs.
