### ISSUE TITLE
Non-root version which has to be triggered manually

### ISSUE THREAD

**Issue by Victor239** [KieronQuinn/AmbientMusicMod#7]
I'm not aware of a open-source song recognition app that works offline, so even being able to do it triggered manually is a very useful feature for privacy enthusiasts. Having it as a normal app in app stores also means more people can be informed of the enhanced root+Xposed version available via the app.

**Comment by KieronQuinn** [comment]
Not possible, it's not the manual trigger that needs Xposed, it's the system patching to make the model work. Please read the FAQ.

**Comment by KieronQuinn** [comment]
> > Not possible, it's not the manual trigger that needs Xposed, it's the system patching to make the model work. Please read the FAQ.
> 
> @KieronQuinn Are we in the same situation now given this issue was created before Android 12 was released and the FAQ says that the Shell having the `CAPTURE_AUDIO_HOTWORD` has become the standard with A12?

This issue is over 2 1/2 years old and predates Android 12, it no longer applies. The version that takes advantage of the permission does indeed allow this.

**Comment by KieronQuinn** [comment]
> I meant if it would be possible even without Shizuku

No, Shizuku uses Shell. It's not possible without Shell access and Shizuku is the best way to use it.
