### ISSUE TITLE
"Trigger when Screen On" not working

### ISSUE THREAD

**Issue by R37RY** [KieronQuinn/AmbientMusicMod#70]
I have tried several combinations of settings in case something was interfering and also disabled the always on display just in case the screen was already considered "on" but I didn't succeed in making it work. The standard recognition period works and shows correctly the songs on lock screen so I guess that all permissions are set, it's only the "trigger when screen on" that is not working for me.

**Comment by KieronQuinn** [comment]
Works fine on all my test devices running the latest build. This is likely an MIUI issue, sometimes disabling "MIUI optimisations" will fix this, otherwise there's nothing I can do since they regularly break stuff in the name of these "optimisations"

**Comment by R37RY** [comment]
I also thought about the MIUI Optimization but I had that already disabled damn... Thanks anyway!
