### ISSUE TITLE
[BUG] Google Smart Lock

### ISSUE THREAD

**Issue by 54m33r4** [KieronQuinn/AmbientMusicMod#76]
If the device is kept unlocked by any trust agent (Google Smart Lock), Neither the Overlay nor the Owner info won't work. I think it's because the app does not detect that the device is in the lock screen while it is unlocked by the trust agent.

Confirmed by using the Lockdown feature. It disables biometrics and also trust agents. 

![image](https://user-images.githubusercontent.com/68902530/176457691-079244db-8c1b-4b74-b054-da4aeb431449.png)
![image](https://user-images.githubusercontent.com/68902530/176457825-cbf9c91e-057b-4ade-be42-7222cb108e6c.png)

Device : Mi A2 Lite (Daisy)
OS : Android 12.1 (Syberia OS 5.4) - Pixel implementation
ROOT : Yes (sui-zygisk)
Everything Up To-Date (v2.0.3 + v1.0.2)

**Comment by KieronQuinn** [comment]
Great spot, it was using [isDeviceLocked](https://developer.android.com/reference/android/app/KeyguardManager#isDeviceLocked()) rather than [isKeyguardLocked](https://developer.android.com/reference/android/app/KeyguardManager#isKeyguardLocked())

Fixed for next version.

**Comment by 54m33r4** [comment]
> Great spot, it was using [isDeviceLocked](https://developer.android.com/reference/android/app/KeyguardManager#isDeviceLocked()) rather than [isKeyguardLocked](https://developer.android.com/reference/android/app/KeyguardManager#isKeyguardLocked())
> 
> Fixed for next version.

Awesome <3

**Comment by KieronQuinn** [comment]
Fixed in 2.0.4
