### ISSUE TITLE
Recording cannot be stopped...

### ISSUE THREAD

**Issue by shanzhaxiaok** [KieronQuinn/AmbientMusicMod#78]
Yesterday is functional, the app could record the sound and show the result on LockScreen.
But when I test it today, I found that whatever music I played, the app just cant recognize it, so I open the app and triggered the "Recognies" button manually, then I found it always show the recording interface, even the "circle" is already closed.
 I dont know if it is still recording or it just stucked in this interface. I have tried the follow steps:
 - Reboot the device;
 - Uninstall the AmbientMusicMod app & Now Playing app;
 - Reinstall that 2 apps;
 - Reboot the device;
 - Change Period/Buffer/Gain/Alternative Encoding/Run on Little Cores/NNFP V3/or other settings...

The problem remains...
![ae0dc4263dc9f4fba732a1cf53f48703](https://user-images.githubusercontent.com/26482631/176587064-54ef6718-1e7a-45a2-9023-b3b83f5aac06.jpg)

**Comment by KieronQuinn** [comment]
It's probably crashing in the background, enable verbose logging and send a log please.

**Comment by KieronQuinn** [comment]
Got a log for the same issue from a user on Twitter, try this APK: https://drive.google.com/file/d/1z-cCN8yfj14oJKbMNVb0bJgkLwT4qdaU/view

**Comment by peetereczek** [comment]
> Got a log for the same issue from a user on Twitter, try this APK: https://drive.google.com/file/d/1z-cCN8yfj14oJKbMNVb0bJgkLwT4qdaU/view

Solved issue for me!

**Comment by KieronQuinn** [comment]
Fixed in 2.0.5

**Comment by shanzhaxiaok** [comment]
Appreciate that~
