### ISSUE TITLE
[Request] Replace blur effect with a darken effect

### ISSUE THREAD

**Issue by PalmDevs** [KieronQuinn/AmbientMusicMod#79]
Replace this blur effect with a darken background effect instead. I personally don't enjoy the blur effect in this context.

[Video...](https://user-images.githubusercontent.com/67689562/176600869-927bb703-4d63-4673-ba06-d0905a4078a0.mp4)

**Comment by KieronQuinn** [comment]
This was an intentional design choice, you don't have to like it.
