### ISSUE TITLE
Often 'Ambient music failed to start' But sometimes it works

### ISSUE THREAD

**Issue by BatLine** [KieronQuinn/AmbientMusicMod#8]
As you can see it worked once and then it's broken again.

I know you need the logs but I'm not sure which ones you need, check screenshot.

Latest magisk & exposed + riru
Oneplus 7 Pro - Oxygen OS 11.0.0.2
Battery optimization for both disabled

![Screenshot_20210420-120308](https://user-images.githubusercontent.com/16621945/115378056-7863ad80-a1d0-11eb-8a21-32e6be626f61.jpg)
![Screenshot_20210420-120330](https://user-images.githubusercontent.com/16621945/115378061-7994da80-a1d0-11eb-85dc-4a880a34dfbb.jpg)

![Screenshot_20210420-115457](https://user-images.githubusercontent.com/16621945/115377355-d643c580-a1cf-11eb-933e-90ce029d1602.jpg)
![Screenshot_20210420-115644](https://user-images.githubusercontent.com/16621945/115377363-d774f280-a1cf-11eb-948d-e4b2da39c5db.jpg)
![Screenshot_20210420-115727](https://user-images.githubusercontent.com/16621945/115377365-d80d8900-a1cf-11eb-8098-4775b38bcbfe.jpg)
![Screenshot_20210420-115737](https://user-images.githubusercontent.com/16621945/115377370-d8a61f80-a1cf-11eb-9c4f-209b294922f7.jpg)

**Comment by KieronQuinn** [comment]
This is fairly normal, if recognition is already running it'll 'fail to start' as it's busy. Just wait a short while and try again.
