### ISSUE TITLE
Add support for AOD custom text

### ISSUE THREAD

**Issue by duramato** [KieronQuinn/AmbientMusicMod#80]
On OxygenOS 12 there's no option to set up a owner info custom text, hence the option for it within AmbientMusicMod fails.
Altough from what I can tell there's a custom text option for the AOD, which could be used for Oneplus and maybe other OEMs with the same option. 
Using this for the now playing info is even more advantageous as the overlay doesn't work on the AOD. 
The setting is set on the variable `aod_display_text` which I'm able to change via Tasker and via ADB secure settings, so I'm guessing would be able to add support from within AmbientMusicMod.

![image](https://user-images.githubusercontent.com/10121067/176713279-9569f52d-cfe2-4a3e-801a-6b0d64875f86.png)

**Comment by KieronQuinn** [comment]
Forgot to say, this was added in 2.1

**Comment by duramato** [comment]
I've just tried it, but it doesn't seem to be working quite right. It just shows some quotes on it.

![image](https://user-images.githubusercontent.com/10121067/219340063-bb3e210c-126e-4608-aae5-2003f47d9199.png)

**Comment by LostName1** [comment]
> I've just tried it, but it doesn't seem to be working quite right. It just shows some quotes on it.
> 
> ![image](https://user-images.githubusercontent.com/10121067/219340269-bbea426f-4f11-46af-856c-59db2e6e9dda.png)

I have installed the app and everything worked perfectly for me except this, the owner text just displays "", is this planned to be fixed?

Device: Oneplus Nord 2 5g
OS: Oxygen OS 13 F.49
