### ISSUE TITLE
[Request] Autoupdate app

### ISSUE THREAD

**Issue by TotallyNotInUse** [KieronQuinn/AmbientMusicMod#83]
Sometimes it's really annoying having to manually update both apps and then the recognition model and I'm pretty sure it would be possible to auto update the app (at least when running in root mode) so it would be nice if you could make that happen.

**Comment by KieronQuinn** [comment]
Automatically updating the app was intentionally not added because of privacy concerns. Automatically updating the database is already in the app.

Updates will be slower from now on, there's been a flurry of them since release for bug fixing but that now seems to be over.
