### ISSUE TITLE
Does not detect proper audio.

### ISSUE THREAD

**Issue by hitarth1999** [KieronQuinn/AmbientMusicMod#84]
I tried to test manually using the recognize button and it records jittery voice always. i have a OnePlus 9R with a Custom ROM called Nameless OS.

**Comment by KieronQuinn** [comment]
Enable alternative encoding, this is a known problem that was fixed with that option

**Comment by hitarth1999** [comment]
Ok, that worked but it still doesn't detect music automatically. Playing from my laptop kept it near the speakers.

**Comment by hitarth1999** [comment]
Thanks!
