### ISSUE TITLE
Online music recognition not recognising correct music

### ISSUE THREAD

**Issue by tejas2004** [KieronQuinn/AmbientMusicMod#85]
Hi there,
I installed the mod and everything is working fine except online music recognition. It either recognises wrong music(image attached) or does not recognises at all.
Offline recognition works fine and it recognises correct all time and the audio is also clear.
![Screenshot_20220702-202915_Ambient Music Mod](https://user-images.githubusercontent.com/42291092/177006062-6688925f-988d-41f2-b6fb-f30f5abd4958.png)
Google App version - 13.25.10.29.arm64 (downloaded from apkmirror split apk)
Also it just recognises all song as summer nights.

**Comment by tejas2004** [comment]
Also tried clean install

**Comment by KieronQuinn** [comment]
Online Music Recognition is handled by the Google app, this is beyond my control.
