### ISSUE TITLE
Updating DATABASE

### ISSUE THREAD

**Issue by Narutoindia** [KieronQuinn/AmbientMusicMod#86]
It is just showing updating database from a long time 
![Screenshot_20220702-212024_Ambient Music Mod](https://user-images.githubusercontent.com/97081100/177007505-ce91109d-1ead-4cba-aa3f-c3a871e9e4cf.jpg)
Any way to fix it?????

>

**Comment by tejas2004** [comment]
Uninstall ambient music mod and now playing and reinstall both

**Comment by KieronQuinn** [comment]
#57
