### ISSUE TITLE
Failed to recognise song

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/AmbientMusicMod#87]
Hi there
Ambient Music Mod suddenly stopped recognizing song, it used to work previously, now don't know  the reason why the mid behaving in a different manner

Android- 12.1

ROM- Stag OS

https://user-images.githubusercontent.com/70900505/177006727-be3b395c-2c7b-4f29-baf8-45471ea74173.mp4

**Comment by KieronQuinn** [comment]
This error is coming from the system music recognition manager, which is not part of Ambient Music Mod. All I can suggest is you try rebooting.
