### ISSUE TITLE
Stuck on downloading song database 

### ISSUE THREAD

**Issue by MSD-3** [KieronQuinn/AmbientMusicMod#88]
I have set now playing Country location to India. 
Still there are no regional songs in the database 
I tried rebooting and also reinstalling the mod and the now playing apk,but it's still stuck on downloading song database.

It currently shows that there are 16,000 songs in the database. I speculate that it has defaulted to US region and isn't changing. 

I have an Unmetered 100mbps connection ,so bandwith isn't an issue .

**Comment by KieronQuinn** [comment]
#57

**Comment by MSD-3** [comment]
This is a different issue I suppose  ![](https://ibb.co/j4CKzKY)

![](  https://ibb.co/xCH2jHV)
