### ISSUE TITLE
[Bug] Unable to recognise ambient music automatically 

### ISSUE THREAD

**Issue by likkai** [KieronQuinn/AmbientMusicMod#89]
I wasn't able to get it identify ambient music around me automatically (like in the lock screen) but it was able to recognise song if I trigger the song recognition in the app manually. I turned on the alternative encoding option and have "Disable at bedtime" off.
However, I did receive warning that another app is using my microphone but there wasn't any. I did turn on the require permission for miui to not kill any of the required processes. 

Device: Xiaomi 11 lite 5g NE (MIUI 13/Android 12)

![IMG_20220703_153018](https://user-images.githubusercontent.com/76016664/177030008-2a901b7f-d86c-4f54-80b1-49eb70ba22d8.jpg)

**Comment by KieronQuinn** [comment]
Sounds like MIUI is preventing the app running in the background. Check you've followed all the steps linked from the battery optimisation page (https://dontkillmyapp.com/xiaomi). If that doesn't help, there's nothing more I can do unfortunately.

**Comment by likkai** [comment]
I've followed the tips from DontKillMyApp page and I scored 100% in the benchmark (no unnecessary killing of background processes) but the issue still persists. Myb I can upload the log or do anything for future optimisation on MIUI?
