### ISSUE TITLE
Ambient Music Failed To Start

### ISSUE THREAD

**Issue by Scientiac** [KieronQuinn/AmbientMusicMod#9]
My device :
Redmi Note 9 Pro Max (Excalibur)
Android -10
I have Magisk Installed 
And EdExposed module is also running.I tried other troubleshooting options but that doesn't seem to work.

When I tested recognition it gave Ambient Music Failed To Start Error. 
Initially I tried to bypass the 'Sound Model Compatibility' but after a reboot It says that it is compatable.

BTW here is the Log Dump : 

[ambient_music_mod_log_dump_2021-04-20T17:10:12.463.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/6343150/ambient_music_mod_log_dump_2021-04-20T17.10.12.463.zip)

**Comment by KieronQuinn** [comment]
There's nothing useful in your log unfortunately, just make sure you've launched Ambient Music before trying a manual recognition and make sure you have whitelisted the required apps in EdXposed if you are using the Whitelist mode.

**Comment by Scientiac** [comment]
![Screenshot_2021-04-20-18-37-51-804_org.meowcat.edxposed.manager.jpg](https://user-images.githubusercontent.com/58177655/115399167-a31d2880-a207-11eb-842c-0ebb6ba4d18f.jpg)![Screenshot_2021-04-20-18-38-02-996_org.meowcat.edxposed.manager.jpg](https://user-images.githubusercontent.com/58177655/115399173-a4e6ec00-a207-11eb-962f-fcbd4bc0dcc0.jpg)![Screenshot_2021-04-20-18-38-19-314_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/58177655/115399178-a6b0af80-a207-11eb-8f23-b061b70d5503.jpg)![Screenshot_2021-04-20-18-38-25-964_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/58177655/115399184-a7e1dc80-a207-11eb-83d5-2779ac7065dc.jpg)

I have ViPER 4 Android and Dolby Installed and the an audio modification  library too , can it hamper the working of your module?

And one more thing , will it show the same error if there is no audio playing around me or a different one?

**Comment by KieronQuinn** [comment]
The error is it trying to start the listening, you get a different response if there's no music. 

I can't see anything wrong here, so there's nothing I can do without actually having the device unfortunately.
