### ISSUE TITLE
Unable to access Now Playing history

### ISSUE THREAD

**Issue by sherloked** [KieronQuinn/AmbientMusicMod#90]
I'm on the latest versions of both the mod and Now Playing. Clicking on Now Playing history goes to its separate app which crashes immediately without showing anything. Screenshot attached showing the same in the recent tasks menu.
![Screenshot_2022-07-04-19-55-43-08_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/43991317/177174387-d002a486-bd79-4891-93a5-0b1d5b99ed8d.jpg)

**Comment by KieronQuinn** [comment]
Is this Oxygen OS?

**Comment by sherloked** [comment]
> Is this Oxygen OS?

Yes, I'm afraid so. OnePlus Nord 2 on OxygenOS 12.1.

**Comment by KieronQuinn** [comment]
Yeah I don't need a log then, already been sent one on XDA. It's caused by OnePlus' fuckery, they're injecting code that's breaking it. Unsure whether I'll be able to fix it.

**Comment by Nive9** [comment]
Alright, glad to hear OnePlus keeps improving their reputation then /s

If it's not fixable, any chance for a .txt export option or anything similar?

**Comment by KieronQuinn** [comment]
The eventual solution might be to replace the history activity with a re-made one, which would be a requirement of replacing the download system since it is reliant on that. It's a big thing to do though so not sure if/when I'll attempt it.

**Comment by Quaradam** [comment]
Same on Realme 9 Pro Plus

**Comment by xilegod026** [comment]
This is also an Issue with the Realme 8 5g, running RealmeUI 3.0 based on Android 12. May just be some ColorOS bs in the background in general ig😕

**Comment by KarstenPH** [comment]
Oppo user here confirming that i have the same issue.

(OPPO A94 CPH2203 • ColorOS 12.1)

**Comment by elFusooo** [comment]
Same problem with oneplus nord 1

**Comment by Donkey-Doug** [comment]
Same issue on a Xiaomi Mi 9T Pro running LineageOS based on android 12 without google play services. I was able to listen once when I first installed ambient music mod, but after that it crashes every time.

**Comment by KieronQuinn** [comment]
> Same issue on a Xiaomi Mi 9T Pro running LineageOS based on android 12 without google play services. I was able to listen once when I first installed ambient music mod, but after that it crashes every time.
> 
> 
>  screen-20230101-173952.mp4

Your issue is different, this issue is about Now Playing History not launching at all due to OEMs injecting libs that cause it to crash (due to the Xposed hooking used by AMM to inject the 32 bit libs and prevent loading missing ones). Could you post a log? I suspect it's looking for a missing app usually included in the GMS bundle.

**Comment by Donkey-Doug** [comment]
> > Same issue on a Xiaomi Mi 9T Pro running LineageOS based on android 12 without google play services. I was able to listen once when I first installed ambient music mod, but after that it crashes every time.
> > screen-20230101-173952.mp4
> 
> Your issue is different, this issue is about Now Playing History not launching at all due to OEMs injecting libs that cause it to crash (due to the Xposed hooking used by AMM to inject the 32 bit libs and prevent loading missing ones). Could you post a log? I suspect it's looking for a missing app usually included in the GMS bundle.

I opened #135, but dont know how to create a log. If you explain the steps, I will create one for you.

**Comment by oceangith** [comment]
Same on OnePlus 10 Pro OOS 13

**Comment by chikkibum** [comment]
hey @KieronQuinn i am facing the same problem on Miui 14 Everything is working fine except the now playing history.  here are the logs. 
can you look into it? 
[logcat.txt](https://github.com/KieronQuinn/AmbientMusicMod/files/10610982/logcat.txt)

**Comment by KieronQuinn** [comment]
You have the same issue. It may be fixable, not sure yet.

**Comment by chikkibum** [comment]
> You have the same issue. It may be fixable, not sure yet.

@KieronQuinn can we somehow get the history from any other means?

**Comment by KieronQuinn** [comment]
You could use a history tracking like Pano Scribbler, which uses the notifications so won't be impacted

**Comment by KieronQuinn** [comment]
I changed hooking method in 2.1 which may fix this, please give it a shot and see if it works.

**Comment by oceangith** [comment]
2.1 fixes mine

**Comment by chikkibum** [comment]
Hey @KieronQuinn great work fixes the history issue for me I'll have to check if it breaks anything else though.

![Screenshot_2023-02-14-01-40-02-156_com kieronquinn app pixelambientmusic](https://user-images.githubusercontent.com/71315985/218566229-2b47d40a-88ef-4eb9-bd59-231cd16980a0.jpg)

**Comment by Donkey-Doug** [comment]
Mine still crashes. I already restarted my phone, but it still crashes.

**Comment by Donkey-Doug** [comment]
> > Mine still crashes. I already restarted my phone, but it still crashes.
> 
> Could you get a log please. Also make sure you have updated **both** AMM and Now Playing, since the actual hooks are in Now Playing.

It works now. I had to wait for the now playing update, which I got the next day.

**Comment by KieronQuinn** [comment]
Assuming fixed for all then.
