### ISSUE TITLE
Song visible in locked camera mode

### ISSUE THREAD

**Issue by peetereczek** [KieronQuinn/AmbientMusicMod#92]
I think that's a bit unexpected behavior. To see song title while making pictures without unlocking the phone.

Latest app, S22 Ultra stock

![Screenshot_20220705-212941_Camera.png](https://user-images.githubusercontent.com/42431204/177401876-86109b97-bc57-45ed-9378-6f3a4af93433.png)

**Comment by KieronQuinn** [comment]
Do you have Adaptive Lock Screen overlay enabled?

**Comment by duramato** [comment]
I'm also experiencing this, even with that option enabled. 
This on OnePlus 8 OxygenOS 12.1

**Comment by peetereczek** [comment]
> Do you have Adaptive Lock Screen overlay enabled? 

It was off. I'll test now with enabled option

**Comment by peetereczek** [comment]
With adaptive lock screen overlay addon is not visible on my lock screen at all

**Comment by peetereczek** [comment]
It's overlapping at unlocking screen when you call app from lock screen, may be related

![Screenshot_20220717-140623_One UI Home.png](https://user-images.githubusercontent.com/42431204/179397539-a9117ab8-f842-4429-bd1f-19eff4f414d7.png)

**Comment by KieronQuinn** [comment]
> It's overlapping at unlocking screen when you call app from lock screen, may be related
> 
> ![Screenshot_20220717-140623_One UI Home.png](https://user-images.githubusercontent.com/42431204/179397539-a9117ab8-f842-4429-bd1f-19eff4f414d7.png)

This one can't be fixed, the OS doesn't broadcast any sort of change when the PIN pad opens for security reasons. Your best bet is to move it to somewhere it doesn't overlap with the PIN entry or the lockscreen, which is usually the bottom of the screen.

**Comment by KieronQuinn** [comment]
Fixed in 2.1.1
