### ISSUE TITLE
My Phone not hearing music 

### ISSUE THREAD

**Issue by Quaradam** [KieronQuinn/AmbientMusicMod#93]
**Realme 9 Pro Plus** not hearing music. I set mic on in "_Now Playing_", _Shizuku_ running too. What i need to do?
 @![Screenshot_2022-07-07-04-02-18-81_432e703e4eb809fda47320666283546a](https://user-images.githubusercontent.com/65819389/177667476-6ff982d3-edb4-44ee-aeee-80a244eff11b.jpg)

**Comment by KieronQuinn** [comment]
Enable alternative encoding and increase the gain, start high and move lower until it's not distorted. If that doesn't work then nothing I can do.
