### ISSUE TITLE
Now Playing error

### ISSUE THREAD

**Issue by Glenry** [KieronQuinn/AmbientMusicMod#94]
![Screenshot_20220711-234016_Ambient Music Mod.png](https://user-images.githubusercontent.com/77478028/178256529-9bec7a79-07a5-4d5d-adc8-39f2cbc821e3.png)
![Screenshot_20220711-234026_Ambient Music Mod.png](https://user-images.githubusercontent.com/77478028/178256580-18d819bb-7f03-49d4-8435-02673ba88957.png)

Everything just got downloaded. SM-A125F.[phone model].

**Comment by KieronQuinn** [comment]
Reinstall both Ambient Music Mod and Now Playing, something got corrupted.
