### ISSUE TITLE
Prepare ambient music mod to work without suzuko app for old and new android versions

### ISSUE THREAD

**Issue by Seandylan123** [KieronQuinn/AmbientMusicMod#95]
Because people are sometimes worry that they can screw up their device with a adb command or routing this is possible by making it run in the background and accessibility services

**Comment by KieronQuinn** [comment]
Not possible, please read the FAQ.

**Comment by Seandylan123** [comment]
> Not possible, please read the FAQ.

Well i think the reason is because it cannot function properly just like power shade in miui because it can easily kill the application if you're on samsung oneplus etc

**Comment by KieronQuinn** [comment]
> > Not possible, please read the FAQ.
> 
> Well i think the reason is because it cannot function properly just like power shade in miui because it can easily kill the application if you're on samsung oneplus etc

I don't think you understand. The core functionality of the app is not possible without Shizuku or root. There is nothing special that accessibility services can fix here.
