### ISSUE TITLE
stuck on Downloading database.

### ISSUE THREAD

**Issue by Venureddyy** [KieronQuinn/AmbientMusicMod#97]
the app always showing as Downloading database . I tried it when connected to wifi and mobile data, but the download never finishes. I have reinstalled the app .No use , still iam facing the problem.

**Comment by dimiboy** [comment]
Happened to my friend, try to reboot the phone, run Shizuku again and it should work

**Comment by Venureddyy** [comment]
Rebooted many times. Still not working.

**Comment by Venureddyy** [comment]
okay. now it's working after many reboots.

**Comment by KieronQuinn** [comment]
#57
