### ISSUE TITLE
Downloading song database error 

### ISSUE THREAD

**Issue by Y0seph** [KieronQuinn/AmbientMusicMod#98]
I've started the app about 3 hours ago and it quarterly is still downloading the database?!

I'm not sure it's supposed to take that long, but it's hard to tell without a progress bar. ![Screenshot_2022-07-14-17-01-12-34_432e703e4eb809fda47320666283546a.jpg](https://user-images.githubusercontent.com/81769739/179073196-b59ead02-a26c-49f7-ac5b-f32fc613a0e7.jpg)

I'm not able to recognize the songs automatically outside the app, but it does recognise on command

**Comment by Y0seph** [comment]
Hey there
I could solve the issue with the classic "clean data".

**Comment by KieronQuinn** [comment]
#57
