### ISSUE TITLE
Download multiple countries' databases

### ISSUE THREAD

**Issue by harshil21** [KieronQuinn/AmbientMusicMod#99]
Is it possible to add a feature where we can download many countries' databases? Maybe that way it could recognize more tracks (in other languages too)

**Comment by lemonnuggets** [comment]
agreed. this would make this already amazing mod just about perfect.

**Comment by Mr-Nobody1** [comment]
same, having problems with that.

**Comment by gattillynx** [comment]
Bumping this idea

**Comment by KieronQuinn** [comment]
Please just react to the issue, no need to add a comment "bumping" it when there's only 3 open issues.

This would probably require an entirely custom download system, Now Playing History and database handling, so it's an enormous request. It might be done eventually, but it's a lot for relatively little gain.
